<?php include "../../../header.php"; ?>
        <font size="5"><b>Interview with Marty Schiff (a.k.a. &quot;Hern&quot;)</b> </font>
        <p>&nbsp;</p>
        <p align="justify">Marty Schiff was known as &quot;Hern&quot; on Out of Control. This interview was done via e-mail on June 15, 2001. Thanks to Marty Schiff for granting this interview. <br>
        </p>
        <p align="justify"><strong>Q: First of all, how are you these days? And what are you doing?</strong></p>
        <p align="justify"><strong>A:</strong> <em>I'm doing well thanks. I am currently living in the Pittsburgh area. I lost my home in the 94 Northridge Earthquake and moved back here to live in a family home that was vacant. I liked it so much I decided to stay. I'm still involved in television and film. I'm writing and producing. I've worked on a few films and several commercials that were shot in the area. I'm also working on a few video and audio projects of my own.</em></p>
        <p align="justify"><strong>Q: What was it like working for Nickelodeon?</strong></p>
        <p align="justify"><strong>A:</strong> <em>It was a blast. Remember, in those days cable was pretty new and Nickelodeon was just starting out. We were the pioneers of what Nickelodeon was to become. OUT OF CONTROL was the first show produced in America just for Nickelodeon. I loved going to work. It was always fresh and exciting. I would be there at least an hour before everyone else. BEFORE the donuts arrived ...in showbiz... that's about as early as you can get.</em></p>
        <p align="justify"><strong>Q: What was your favorite part about working on Out of Control?</strong></p>
        <p align="justify"><strong>A:</strong> <em>The cast and crew of OUT OF CONTROL were very special. It all clicked. We worked together very well it was always fun. Dave, Diz, Dave Stenstrom (Waldo), and Jill (Angela) were all wonderful people to work with. It was a very talented group. You could feel that we knew we were all part of something big..</em></p>
        <p align="justify"><strong>Q: How did the concept for Out of Control come about?</strong></p>
        <p align="justify"><strong>A: </strong><em>As far as I know it was the brain storm of Bob Hughes and Larry Sulkis. I'm not really sure about that.</em></p>
        <p align="justify"><strong>Q: From the comments I've seen you post online (Yesterdayland for example), and the fact that you were receptive to this interview, it's clear that working on OOC was a great time in your life. What makes the show so memorable for you?</strong></p>
        <p align="justify"><strong>A:</strong><span class="style4"><em> It was so new and felt so important. Every moment was a memory for me. I don't know about the other cast members, but I truly felt we were going to be on the air forever. If you watch the episodes closely some of our guest stars went on to have very lucrative careers. Dennis Miller is one of those guest stars. (Dennis and I went to college together but I had nothing to do with him being cast.) Working with the DUCKS BREATH MYSTERY THEATER was incredible. The &quot;Ducks&quot; had some amazing comic energy and wrote some of the most memorable sketches on the show. Jim Turner's song &quot;A REALLY BIG WORLD&quot; is brilliant and I still use Bill Allards &quot;TOO...MUCH...FUN&quot; when life is spinning &quot;out of control&quot;. Merle Kessler, Dan Coffey and Leon Martell along with Jim and Bill created some of the most hysterical characters I have ever seen. It was truly an honor to work with them darn Ducks. </em></span></p>
        <p align="justify"><em>I had a party the night we were supposed to be renewed. I found out the night of the party there were to be no future episodes of OUT OF CONTROL. I was very shocked to hear we were not picked up for more shows. There are only 26 episodes of OUT OF CONTROL. It ran for 8years in reruns. My kids MUST refer to Nickelodeon as &quot;the network that Daddy built&quot; or they get grounded. The show is very funny and really holdsup. My kids watch tapes of OUT OF CONTROL today and love it...they better!</em></p>
        <p align="justify"><strong>Q: Many OOC skits were filmed at remote locations. Where did you get to travel too? </strong></p>
        <p align="justify"><strong>A:</strong><em> Well, I stayed in the Los Angeles area. ESKIMO PIE, where Dave and I are in a plane most of the show, was filmed at Van Nuys Airport, SNOW FISH was shot in Santa Monica as was SIBERA. MY BROTHER'S A MONSTER, BACK YARD BAR B QUE and Jill's DINOSAURS were all filmed at one of the producers homes. MERMAIDS, BRIEFCASE HARVEST, and a few other spots were shot in Malibu. That was our last day of remotes and we had a big cast party on the beach. Oak O'Connor, the shows production genius, who created all the props for the show including &quot;HA HA the comedy computer&quot; and &quot;the Hurry Up Machine&quot; broke his foot during Briefcase harvest. He came back to the cast party...wearing a cast! Dave did get to travel for CAR HOP and WINSTEADS, FOUNTAIN FAIRY and few other segments that were shot in Kansas City,home-town to Bob Hughes and Larry Sulkis.</em></p>
        <p align="justify"><strong>Q: Where was OOC filmed? </strong></p>
        <p align="justify"><strong>A</strong>: <em>OUT OF CONTROL was shot at Valley Production Center in Van Nuys, California.</em></p>
        <p align="justify"><strong>Q: Out of Control used many creative skits, such as &quot;Let's Eat&quot;, &quot;Hurry Up&quot;, and &quot;It's Probably True&quot;. How did these ideas come about?</strong></p>
        <p align="justify"><strong>A:</strong> <em>Again, those were the brain children of Bob and Larry, Oak O'Connor and a few of the other producers. We were all cast in the show after it was already created. Many of the segments were improv'd and ad-libbed. We'd get to a location and the segment producer would say &quot;Okay...what do you want to try?&quot; and off we'd go. SNOW FISH (EXOTIC PET STORY) was mostly off the top of our heads..</em></p>
        <p align="justify"><strong>Q: Do you think there will ever be a reunion of OOC? Also, who owns the rights to the show, and is there any chance it could be rebroadcast, or released on video?</strong></p>
        <p align="justify"><strong>A:</strong> <em>As far as I know Nick owns the show. Dave has talked about getting the rights to it and re-releasing it on video and DVD. I don't think there will ever be a reunion. I know we were very popular when we were on and I run into fans all the time. Maybe if enough people let Nickelodeon know they want to see it again there could be some re-broadcasts. I will say this much, if there were a reunion I'd be there.</em></p>
        <p align="justify"><strong>Q: Do you think Nick programming helps actors careers, look at everyone else who has succeeded on NICK?</strong></p>
        <p align="justify"><strong>A: </strong><em>I think beside Alanis and Dave there weren't too many careers launched from the &quot;old&quot; days on Nick. Now it's a much more popular network. In the mid 80s when we were on, Nick, and Cable for that matter, were in their infancy. Today the stars on nick are truly stars and they have a better chance of moving on to bigger things.</em></p>
        <p align="justify"><strong>Q: The cast was interesting to say the least, and everyone portrayed their part very well. How were these parts tweaked by the actors themselves?</strong></p>
        <p align="justify"><strong>A:</strong> <em>Well, in the beginning we were given lines and brief ideas of the characters from Bob Hughes, then set loose to create our characters. Hern was pretty much created during my audition. Waldo was pretty much created by Dave Stenstrom as was Angela for Jill Wakewood. Dave was pretty much Dave and Diz IS Diz. By the way, Waldo was added AFTER the pilot episode.</em></p>
        <p align="justify"><strong>Q: Why did the show only last for 26 episodes? It obviously was successful, since it aired in reruns until around 1991.</strong></p>
        <p align="justify"><strong>A:</strong><em> If you watch children's programming you will see that the same episodes air time and time again. Kids LOVE repetition and the &quot;Familiar&quot;. My own kids will watch the same Rugrats episode over and over again, the same with any of their favorites. It's just the reality of the genre. There were times where OUT OF CONTROL was on seven days a week , four times a day. We probably went through every episode every two weeks.</em></p>
        <p align="justify"><strong>Q: I probably should ask something about Dave Coulier. What was he like working with?</strong></p>
        <p align="justify"><strong>A: </strong><em>I loved working with Dave. My background is theater. I'm a classically trained actor who happens to have a knack for comedy. Dave is a comedian with a background in comedy. We worked so well together. I loved doing scenes and remotes with Dave. He's one of the few people that can consistently crack me up on camera. We had a great energy together. He's truly one of the funniest people alive. We stay in touch via emails, a very occasional phone call and regards through friends.</em></p>
        <p align="justify"><strong>Q: Have you kept in touch with the other cast members? What are they doing these days?</strong></p>
        <p align="justify"><strong>A:</strong> <em>Well I have to admit I'm very behind on keeping in touch. I know Dave has a few projects in the works, I just caught him on a made for Disney Movie. The last I heard on the others was Diz is still doing her one woman show in Hollywood. Dave Stenstrom (Waldo) has joined a seminary and was going to become a Priest (I kid you not), and Jill moved back to Chicago where she is producing TV projects.</em></p>
        <p align="justify"><strong>Q: Other than my page, and the one at Yesterdayland, are there any other OOC sites? Also, do you have a website?</strong></p>
        <p align="justify"><strong>A:</strong> <em>I'm not aware of other sites but I do keep my eye out for them. OUT OF CONTROL is mentioned on many sites and there is even one that lists a song written by a marching band in Texas called &quot;MY DINNER WITH HERN BERFORD&quot; I have a site called THE TALENT FACTORY www.talentfactory.com The Ducks have a site http://www.ducksbreath.com/ducks/bio/dkbio.htm where they don't mention OUT OF CONTROL. I'll be sure to send them a nasty email after I'm done here.</em></p>
        <p><a href="index.htm">Back</a> to Out of Control. </p>
<?php include "../../../footer.html"; ?>
