<?php include "../../../header.php"; ?>
        <p align="center"><font size="6"><b>Other Nick Gems</b></font>
        </p>
        <p>&nbsp;</p>
         <p align="justify"><strong>Brad Kane</strong><br>
         I think Brad Kane had his own show at one time, but after it was cancelled, he was shown in short five minute segments to bring us the &quot;coolest kid stuff&quot; throughout the 1980s. I've kind of wondered what ever became of him, because he had a great deal of acting ability, and would have made an ideal talk show host or news anchor.</p>
         <p align="justify"><strong>Fast Food</strong><br>
           A short, five minute piece of animation. It dealt with three cooks, all of whom needed to use a frog in a jar as green food coloring in what they were cooking for St. Patrick's Day. They end up fighting over it, until the announcer informs us: &quot;I've made a terrible mistake. It's not St. Patrick's Day, it's Valentine's Day.&quot; The glass that they frog was in is shown broken on the floor and the frog has escaped. The three cooks then look at a red bird who says: &quot;Polly wants a cracker. Polly does not want to be a cracker.&quot;</p>
         <p align="justify"><strong>The Ratties</strong><br>
           Short, 5-10 minute segments about a family of rats. There were &quot;The Fattie Brothers&quot;, Tattie, a baby, and others.</p>
         <p align="center"><strong>Sports Cartoon</strong><br>
           <img src="sportscartoon1.gif" width="160" height="120"></p>
         <p align="justify">Short segments about a small, bully cat and a large, slow hippo. Sometimes there were also small hippos, large cats, and there was a skinny dog occasionally too. They were usually involved in some sporting event, and of course the hippo would win because he's the good guy. The dog usually served as the referee, and it usually ended with the hippo giving us a thumbs up.</p>
         <p align="justify">&nbsp;</p>
         <p align="justify"><strong>Stick Stickley</strong><br>
           Host of Nick in the Afternoon during the mid-1990s. And oh yeah, he's a popsicle stick.</p>
         <p align="justify"><strong>Christmas Come to Tattertown</strong><br>
           Not a TV show, but rather a short Christmas &quot;movie&quot; Nick always aired around Christmas. It was about a young girl who somehow go sucked into a magical world where everything that any human had ever lost was. It's a cartoon I'd love to see again, because it sounds like it has a lot more symbolism in it than a twelve year old (that's about how old I was the last time I saw it) would pick up on.</p>
         <p align="justify"><strong>Various Others</strong><br>
           There was a short of The Cat Came Back<br>
           There used to be commercials where Abraham Lincoln was sitting in a barber shop, and there was a Barber Shop Quartet who sang: &quot;Nickelodeon.. our TV Network.. Nickelodeon.. The place for kids.. Nickelodeon&quot; and all their wigs flew off.<br>
           There was a commercial that had an anteater (I guess that's what it was) eating spaghetti with its snout. When it had eaten it all, the plate said &quot;Nickelodeon&quot;, and the anteater burped.<br>
           There was also a commercial where a grilled cheese sandwich melts and spells out &quot;Nickelodeon&quot;.<br>
           There was one where a kid wakes up in the middle of the night on his couch and walked to his bed. On his way, he passes a rug that says &quot;Nickelodeon&quot;, and a toaster with &quot;Nickelodeon&quot; coming out of it. On his way to bed he says &quot;Nickelodeon&quot; a few times, and when he gets into bed he &quot;dreams&quot; &quot;Nickelodeon&quot;.<br>
           Who can ever forget the Toys R Us Super Toy Run or Nick Takes Over Your School ? There was also a Nickelodeon Stocking Stuffer Give Away , and Easter Egg Hunt '89 (obviously in 1989). In the Easter Egg hunt, when you saw an easter egg during a Nick show, you called a number.There was also a contest where if you spotted Looney Tunes character during a Nick show, you called and reported it, but as one kid put it (on TV): &quot;the phone company freaked, and demanded that Nick cancel the contest. We said sure, but not before we'd given away every last bit of looney loot.&quot;</p>
         <p align="justify">There was one where this boy was riding his bicycle to Nickelodeon Studios in Orlando, and people were always trying to side track him.</p>
         <p align="justify">There was one where a scientist was trying make himself into a kid so that he could watch Nickelodeon. He always screwed up though. Once he turned himself into a baby goat (a kid), he also went back in time to become a kid, but it was before TV was invented, and once he turned himself into a kidney, and once into a baby.</p>
         <p align="justify">There was one where a little girl read a story about cows dancing</p>
         <p align="justify">There was also a terrorist group called &quot;A.W.F.F.U.L.&quot; (&quot;Adults Who Find Fun Unbearably Lonesome&quot;), who was always trying to sabotage Nick shows and make school last all summer. I was always against them in the late 1980s, but if they returned to sabotage the shows Nick now airs, I'd probably cheer them on.</p>
         <p align="justify">Remember those three dinosaurs that wore sunglasses and sang? I think they were called &quot;The Doowhopasaurs&quot;. They looked like Brontosaurus', and they sang: &quot;I'm here with my friends.. (Nickelodeon)... The sun and rays... Nickelodeon!&quot;</p>
         <p align="justify">There was also another dinosaur. This one looked like a Tyrannosaurus Rex. He drove around in a convertable.</p>
         <p align="justify">There was a promo that had a satellite called &quot;Slime One&quot; return to Earth with some &quot;startling findings&quot;. It revealed that &quot;Venus has a desertous terrain covered in what appear to be sea monkeys.. but no kid's network.. Saturn is made entirely on crunchy caramel and chewy nougat, but no kid's network, and, while there are no life forms visible, Neptune does have one radio station that plays Labamba all day... but not kid's network! Based on these findings we can now say that Nickelodeon is the only kid's network in the entire known universe.</p>
         <p align="justify">There was one where we eavesdropped on the Nickelodeon switchboard, were Elmer Fudd was making party plans. He called and invited Inspector Gadget, who said &quot;I'll be right there,&quot; Ruth Martin (of Lassie), who said &quot;I have to go to Capital City in the morning to do some shopping, but I'll be back in the early afternoon&quot;, someone else (can't remember who.. Duckula maybe?) who says &quot;I'll see if I'm free to come to dinner.&quot; Unfortunately Matt (of Don't Just Sit There) could not attend because he had to run some errands for Mrs. Wilson (of Dennis the Menace). Matt's reacton to this was: &quot;Oh man I hate it when she makes me pick up pantyhose!&quot;</p>
         <p align="justify">There wasone entitled &quot;Nickelodeon, the first kids' network, presents: A Walk in the Park.&quot; There was this kid walking in the park with his grandfather, and the kid ask &quot;Grandpa, what was it really like when you were a kid?&quot; to which the grandfather replies &quot;Mostly we read books, sang songs, and ate bugs.&quot; The kid seems unable to believe a reality that didn't include Nickelodeon, and asks &quot;No Finder's Keepers? No Double Dare? No Duckula?&quot;.</p>
         <p align="justify">Nick Johnson remembers: &quot;..there's one where there's a platter and there's like an opera singer on it and the waiter covers it with an orange cover that said 'Nickelodeon.'&quot;<br>
         &quot;There was another where a guy drinks a cup of water with his nose. These are pretty hard to describe.&quot;<br>
         &quot;There was one more where there was a guy watching TV and there's this monster who eats the TV and the guy rides the monster I guess.&quot;<br>
         &quot;The one where a firework bounces of an astronaut, a satellite and an asteroid and it explodes saying Nickelodeon.&quot; </p>
         <p align="justify">Kevin submits:</p>
         <p align="justify">&quot;'Dog Brain', the one with the sleeping dog where you get to see his dreams and he farts at one point. The second is one of the great works to come from the Aardman Studios, &quot;Creature Comforts&quot;, with all the zoo animals being interviewed in england, the crazy brazillian panther, and the ever whimsy and innocent polar bears. You can actually see this old gem at www.atomfilms.com. Just go to the main page and do a search for &quot;creature comforts&quot; and it comes right up.&quot; </p>
         <p align="justify">Jeff submits:</p>
         <p align="justify">&quot;I remember two more commercial break things that you don't have listed. The first one was animated. It had a dog and a bird in a cage, and the dog says &quot;woof&quot;, and the bird says &quot;Nickelodeon.&quot; Then the dog says &quot;woof&quot; again, and the bird says &quot;Nickelodeon&quot; again. Then the bird says &quot;Woof&quot;, and the dog says &quot;Nickelodeon&quot; in a scooby dooish voice. </p>
         <p align="justify">The other one had three dogs in orange jump suits disco dancing, and then I think at the end a an orange disco ball comes down that says Nickelodeon on it.&quot; </p>
         <p align="justify">Kristyn submits: </p>
         <p align="justify">&quot;This one was called, &quot;Inside Out Boy&quot; it was a short cartoon that played sometime indetween some shows, it was a kid swinging on his swing and he swings so high he goes over the bar and when he does he turns inside out and it's about him dealing with kids who make fun of him.&quot; </p>
         <p align="justify">Ivy says: </p>
         <p align="justify">&quot;I remember a few commercials from the early days of Nickelodeon. There was the one with two green aliens in a space ship flying through space and at the end they sat in front of an outer space drive in theater with Nickelodeon written across the screen and the infamous &quot;Nickelodeon&quot; music playing in the background. </p>
         <p align="justify">Also there was the one with three or four Weimaraners that were placed on top of white boxes in different poses. At the end I think there was a giant orange ball with Nickelodeon on it. </p>
         <p align="justify">From the days of Nick JR I remember enjoying the music videos they had on as fillers between shows. I think they were called &quot;Kid Tunes&quot; or &quot;Kid Bops&quot;. They had famous singers singing. I know that there was one called &quot;A Little Kid's World&quot; with a woman in a big red hat and &quot;The Locomotion&quot; where some kids were forced to work on a train by a very ugly guy with bucked teeth. </p>
         <p align="justify">Another commercial was where they had an announcer say that &quot;Nick is here everyday&quot; and he would list every kind of day you could think of and he finished off with&quot; Nick here is here everyday, except on April Fool's day. Just kidding. Nick is here everyday!&quot; </p>
         <p align="justify">Then there was a commercial with a bunch of blue ants at a picnic and they were singing &quot;Nick Nick Nick Nick Nick-O-Lodeon!&quot; to a slow paced melody. </p>
         <p align="justify">The same song was used for a commercial where a girl was throwing an orange bone with Nickelodeon written on it to her dog and the bone flew threw the air and the dog caught it in its mouth at the end. </p>
         <p align="justify">I don't remember too much of this commercial, but it was for Looney Tunes, when they were on Nickelodeon. All I know is that some person was singing to an opera song about how Looney Tunes were a great thing to watch. </p>
         <p align="justify">There was a Christmas movies they used to show about toys that came to life and if they were seen by humans they &quot;died&quot;. It had a doll named Apple, a tiger stuffed-animal, a Barbie doll, and an old teddy bear. The story revolved around the tiger and how he did not want to be replaced by any new toys that would be given to his owner at Christmas. Apple tried to stop the tiger from taking the place of a warrior woman doll, who was set free and ran amuck around the house. At the end the tiger and Apple were able to persuade the woman warrior doll back in her box by singing a song on how great she was. The tiger and Apple became better friends then they were before and the tiger learned that just because he was an old toy, did not mean his owner didn't love him any less. I think this was made by Jim Henson and it was on when Nickelodeon still owned The Muppet Show and other Jim Henson creations. </p>
         <p align="justify">Around Halloween they used to show a cartoon about two girls and a boy and how they were going to a haunted house to put a dead cat's spirit to rest. I think it was supposed to be a NickToon, but the idea was canceled. </p>
         <p align="justify">There was yet another commercial about a monkey on an orange balloon, who wanted to pop it. He had a safety pin that wouldn't work and in the end he put his finger on the pin and ended up popping himself. </p>
         <p align="justify">In another commercial they had kids from different parts of the world, I think this was done in clay-mation, and they sat on chairs, while a soothing voice said &quot;Nick, Nick, Nick&quot; and that's all I remembered. </p>
         <p align="justify">Still another commercial that showed kids in orange jumpsuits painting an orange blimp on the ground. In the end the blimp said Nickelodeon, </p>
         <p align="justify">Yet one more commercial had a pair of glasses, novelty teeth, and two different sized eyeballs that were suspended in the air by strings. The weird face sang the Nickelodeon song and had two hands in straw hats with red lips painted on them singing the backup. </p>
         <p align="justify">There was a show called &quot;U 2 U&quot; that had kids send in their drawings and ideas, so that they could be placed on TV. </p>
         <p align="justify">Nickelodeon also had these weird scenes that were showed with the seasons. For instance, in winter this strange machine would shot balls of white stuff at a stage and the balls would turn into a snowman, presents, and a tree. In summer they had an umbrella, a sandcastle, and a palm tree? I forgot what the other two seasons had. </p>
         <p align="justify">During Thanksgiving they used to show a movie about two poor kids who only had a can of beans for their Thanksgiving dinner. That night the kids were whisked away to a magical world inside their kitchen with food that came to life. The next morning their kitchen was full of food and they were able to have Thanksgiving dinner. </p>
         <p align="justify">I remember that Nickelodeon also showed some movies. There was one that took place in the world of ants and it followed this one specific ant that could not grow another segment to his body and how he was stuck as a kid. They also played an animated version of &quot;Black Beauty&quot;, &quot;Ivanhoe&quot;, and &quot;The Hunchback of Notre Dame&quot;. </p>
         <p align="justify">Lastly, I used to love it when Nick used to own the rights to The Muppets. They used to show Jim Henson's version of The Frog Prince and Cinderella, not to mention the wonderful Christmas special. From The Frog Prince I still remember Robin singing Sweetums to sleep and the evil witch yelling &quot;Have a popover Froggie!&quot; </p>
         <p align="justify">During the fall there was this one special about a donkey, dog, rooster, and a cat who played musical instruments and stopped their old, evil owners from doing something bad. </p>
         <p align="justify">Also there was a short segment during Nick JR. called &quot;Muppet Time.&quot; </p>
         <p align="justify">I miss so many of the old shows.&quot; </p>
<?php include "../../../footer.html"; ?>
