<?php include("../header.php"); ?>
<P><FONT size=4>Tim Cahill and Julie McNally Cahill Talk About My Gym Partner’s a Monkey</FONT></P><P><B><I><SPAN>Who came up with the idea for the show - and tell the truth!</SPAN></I></B><B><I><SPAN> </SPAN></I></B></P>
<P><SPAN>Tim: I did it all!<SPAN>&nbsp; </SPAN>Ha, ha.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Julie: Wow… There were a couple different things.<SPAN>&nbsp; </SPAN>One of which was a friend of ours told us a story about how he went to an alternative school as a kid.<SPAN>&nbsp; </SPAN>It was a school without walls and everything was real lax.</SPAN></P>
<P><SPAN>Tim:<SPAN>&nbsp; </SPAN>I’d never heard of this.<SPAN>&nbsp; </SPAN>I was like, “What’s a school without walls?”<SPAN>&nbsp; </SPAN>I guess they’d have classes in a larger area and kids could just wander from one little group to the next.<SPAN>&nbsp; </SPAN>It seems crazy!<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Julie: And there was a monkey somewhere in the school and he’d go hang out with the monkey.<SPAN>&nbsp; </SPAN>So we thought that was a funny story and sort of got us thinking in those terms.<SPAN>&nbsp; </SPAN>Like, what if there was a kid whose best friend was a monkey.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Tim: It sort of morphed into this one kid with a monkey into this whole school and him trying to just survive the experience of being in this school with wild animals.<SPAN>&nbsp; </SPAN>We thought this was a funny idea, ripe with possibilities. </SPAN></P>
<P><SPAN>Julie:<SPAN>&nbsp; </SPAN>So we went from there. And developed it and pitched it to Cartoon Network.<SPAN>&nbsp; </SPAN>It was the first place we pitched.<SPAN>&nbsp; </SPAN>We actually came in with another show idea and we took this along even though we weren’t quite finished with it yet.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Tim: Yeah, we came in to pitch something else and after we we’re finished, the head of development said, ‘Well do you have anything else?’<SPAN>&nbsp; </SPAN>We were like, ‘Well, we have this other idea but we haven’t really locked it down yet.’ And he went, ‘That’s the one we should do.’<SPAN>&nbsp; </SPAN></SPAN></P>
<P><B><I><SPAN>Do you draw on your own childhood and school experiences for the show?</SPAN></I></B><B><I><SPAN> </SPAN></I></B></P>
<P><SPAN>Tim: We sit down with the writers and we try to figure out common experiences everyone has in middle school and pull from that.<SPAN>&nbsp; </SPAN>And we then try to figure out how animals would react to a school dance or how they would celebrate Halloween at school.<SPAN>&nbsp; </SPAN>We’d come-up with the basic idea and then try to figure out the “animal” take on that.<SPAN>&nbsp; </SPAN>Some of the things get ridiculous.<SPAN>&nbsp; </SPAN>We have an episode where they’re trying out for the cheerleading squad.<SPAN>&nbsp; </SPAN>And we think, what exactly would an animal cheerleader look like and how would that play out? So we sort of come-up with ideas taking it from that angle.</SPAN></P>
<P><SPAN>Julie: Yeah, the sort of things that every kid or adult could relate to but with an animal spin on it.<SPAN>&nbsp; </SPAN>It seems like it’s ripe with possibilities because we’ve all gone through at least twelve years of school and there are all sorts of things that happen.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Tim: Oh I remember an episode that really cashed in on this.<SPAN>&nbsp; </SPAN>We wanted to do a Valentine’s Day episode but instead of the kids having a crush on another kid in school, wouldn’t it be funny if the teachers have a crush on one of the other teachers?<SPAN>&nbsp; </SPAN>How would an animal react to crushes and trying to attract someone of the opposite sex?<SPAN>&nbsp; </SPAN>We started looking into how animals do that in nature and it got to be really silly.<SPAN>&nbsp; </SPAN>So we had this character going through everything animals do to attract one another but in a school situation and it turned out to be a really funny episode.<B><SPAN>&nbsp; </SPAN></B></SPAN></P>
<P><B><I><SPAN>Did you decide what animals you were going to use before you created the characters, or did you create the characters first, then decide what animal made the best sense?</SPAN></I></B><I><SPAN> </SPAN></I></P>
<P><SPAN>Julie: We sort of came-up with character types first.<SPAN>&nbsp; </SPAN>Tim tends to think more visually, since he’s an artist, and I’m more the word person.<SPAN>&nbsp; </SPAN>I know he came up with the characters, so visually this gorilla looks good here with this small monkey or tall giraffe.<SPAN>&nbsp; </SPAN>We came-up with character types.<SPAN>&nbsp; </SPAN>We knew we wanted Windsor to be sort of brainy, and it doesn’t necessarily match his big physical type because you’d think the gorilla would be threatening.</SPAN></P>
<P><SPAN>Tim: And we wanted the tall girl, Ingrid the giraffe, to be the girl who over the summer became taller than all the boys in her class.<SPAN>&nbsp; </SPAN>And she tries to hide that fact by sort of slouches a lot.<SPAN>&nbsp; </SPAN>Slips, the python, is the laid back guy because he doesn’t really have a spine.<SPAN>&nbsp; </SPAN>We tried to mix-up sizes for the group and then tried to figure out what kind of archetype can we plug in to this character to make it work as a group.</SPAN></P>
<P><SPAN>Julie: And a lot of them have evolved as we started writing the show.<SPAN>&nbsp; </SPAN>Like, Lupe is a pretty strong, feisty character.<SPAN>&nbsp; </SPAN>We always saw her that way, into the school gossip, but she’s become a fireball and that’s come out of writing her on the show.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Tim: You know what’s funny, as we’ve developed stories we come-up with characters that help drive that particular episode.<SPAN>&nbsp; </SPAN>And then we end up liking this character so much that we put them in the school.<SPAN>&nbsp; </SPAN>A couple of characters we thought we’d use once keep showing up again and again.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><B><I><SPAN>Did you research exotic animals to help you with their personalities/characteristics, or just fake it?</SPAN></I></B><B><I><SPAN> </SPAN></I></B></P>
<P><SPAN>Tim: You think we would, but we didn’t.<SPAN>&nbsp; </SPAN>Not really. We were just trying to come-up with funny situations.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Julie: Again in the course of writing the show we’ve done some research like, Tim referenced the episode where Mr. Hornbill has a crush on Mrs. Tusk we did some research there on animal mating rituals.<SPAN>&nbsp; </SPAN>We watch Animal Planet and Discovery Channel.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Tim: We try to keep our ears open for things happening in the news about schools or animals.<SPAN>&nbsp; </SPAN>And we try to use the story in an episode.<SPAN>&nbsp; </SPAN>There was this story that scientists were using monkeys to operate robots. And I thought, “Wow, this is wild.”<SPAN>&nbsp; </SPAN>So I told one of our writers, that we have to do an episode where Jake gets a robot arm stuck on his hand during a science project for school and then it just goes crazy.<SPAN>&nbsp; </SPAN>And it turned out to be really funny.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><B><I><SPAN>You're the first married couple to&nbsp;be co-creators of&nbsp;a show on Cartoon Network.&nbsp; How does your work influence your relationship? Do you have a "No Gym Partner" policy at home?</SPAN></I></B><B><I><SPAN> </SPAN></I></B></P>
<P><FONT size=2>Julie: Yes, it’s 24-hours non-stop, <I>Gym Partner</I>.<SPAN>&nbsp; </SPAN>It is hard to implement any such rules.<SPAN>&nbsp; </SPAN>It’s pretty much there in some form all the time.</FONT></P>
<P><SPAN>Tim:<SPAN>&nbsp; </SPAN>We say we’re not going to talk about it at home but we end up doing it anyway.</SPAN></P>
<P><SPAN>Julie:<SPAN>&nbsp; </SPAN>Yeah we’ve tried it but I think we need some 12-step program.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Tim: We’ve worked together for quite awhile.</SPAN></P>
<P><SPAN>Julie:<SPAN>&nbsp; </SPAN>We’ve never not worked together, really, so it’s part of our whole relationship.<SPAN>&nbsp; </SPAN>It would be weird not to work together at this point. </SPAN></P>
<P><B><I><SPAN>What kind of cartoons did you love growing up? How did they influence you?</SPAN></I></B><B><I><SPAN> </SPAN></I></B></P>
<P><FONT size=2>Julie:<SPAN>&nbsp; </SPAN>I’m between two brothers, so I either had to watch <I>Johnny Quest</I> or <I>Speed Racers</I>.<SPAN>&nbsp; </SPAN>I watched whatever was on, Looney Tunes.<SPAN>&nbsp; </SPAN></FONT></P>
<P><SPAN>Tim:<SPAN>&nbsp; </SPAN>I was a huge Warner Bros. fan.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><B><I><SPAN>Where do you think Jake ranks among the great animated primates - Magilla Gorilla, Bingo from the Banana Splits, Gleek from Superfriends, Grape Ape, and Mojo Jojo?</SPAN></I></B><B><I><SPAN> </SPAN></I></B></P>
<P><FONT size=2>Julie:<SPAN>&nbsp; </SPAN>He’s gonna be up there.</FONT></P>
<P><SPAN>Tim:<SPAN>&nbsp; </SPAN>He’s pretty wacky.<SPAN>&nbsp; </SPAN>Tom Kenny is his voice and he contributes a lot to Jake’s wackiness.<SPAN>&nbsp; </SPAN>I think he’s gonna be well-liked and kids are going to get a big kick out of him.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Julie: It’s hard to put a ranking on him since we’re so close to him.<SPAN>&nbsp; </SPAN>It doesn’t seem fair to the other primates.<SPAN>&nbsp; </SPAN>I think he’ll be very likeable with both kids and children.</SPAN></P>
<P><STRONG><EM><FONT size=2>Adam is the only human in the school.<SPAN>&nbsp; </SPAN>Will we see Adam’s parents or other humans in episodes?<SPAN>&nbsp; </SPAN>Will any episodes take place outside of school- any sleepovers at Jake’s house?<SPAN>&nbsp; </SPAN></FONT></EM></STRONG></P>
<P><SPAN><FONT size=2>Julie:<SPAN>&nbsp; </SPAN>Adam has a human girl who he has a crush on who used to go to his old school.<SPAN>&nbsp; </SPAN>Her name is Kerry.<SPAN>&nbsp; </SPAN>So she’s in several episodes.<SPAN>&nbsp; </SPAN></FONT></SPAN></P>
<P><SPAN><FONT size=2>Tim:<SPAN>&nbsp; </SPAN>When we were in development we talked about his parents and introducing them.<SPAN>&nbsp; </SPAN>But for some reason we kept writing stories about Adam and the school.<SPAN>&nbsp; </SPAN>We kept postponing introducing them.<SPAN>&nbsp; </SPAN>And right now we’re finishing up writing our second season and we still haven’t taken the time to think about his parents.<SPAN>&nbsp; </SPAN>Hopefully, as we start our third season, we’ll get a chance to bring them around.<SPAN>&nbsp; </SPAN>Occasionally we’ll see kids from Adam’s neighborhood who think he’s weird that he’s going to this other school, especially an all-animal school.<SPAN>&nbsp; </SPAN></FONT></SPAN></P>
<P><SPAN><FONT size=2>Julie:<SPAN>&nbsp; </SPAN>There’s a sleepover episode at Adam’s house. Jake and Slips just show up and it just so happens that the next morning Adam has a date with Kerry.<SPAN>&nbsp; </SPAN>So he has to wake up really early and that’s the night that Jake and Slips come over and of course all sorts of hijinx occur.<SPAN>&nbsp; </SPAN>We have an episode where Adam has a birthday party at Chuck E. Cheese’s type place and his worlds collide.<SPAN>&nbsp; </SPAN>The animals show-up even though Adam doesn’t want them there because he’s afraid they’ll embarrass him.<SPAN>&nbsp; </SPAN>And Adam’s<SPAN>&nbsp; </SPAN>human friends are there but he has to try to keep them apart from the animals.<SPAN>&nbsp; </SPAN></FONT></SPAN></P><br>Source: Cartoon Network Pressroom (Now defunct)</span>
<?php include "../footer.html"; ?>
