<?php include("../header.php"); ?>
<P><FONT size=4>Craig McCracken Talks About Foster's Home for Imaginary Friends</FONT></P><P><B><SPAN>Where did the idea for <I>Foster’s</I> come from?</SPAN></B></P>
<P><SPAN>From my imagination!<SPAN>&nbsp; </SPAN>After making the <I>The Powerpuff Girls Movie</I>, I wanted to take a break from drawing the same characters I had been drawing for 11-12 years.<SPAN>&nbsp; </SPAN>I was just doodling and drawing these random characters in my sketchbook and thought I really would love to do a show where I could invent new characters whenever I wanted and have a fresh universe for them to appear in.<SPAN>&nbsp; </SPAN>Typically with <I>The Powerpuff Girls</I> whenever I created a new character, it was a bad guy.</SPAN></P>
<P><SPAN>Along the way I stumbled across the idea of imaginary friends, and that seemed like a good jumping off point.<SPAN>&nbsp; </SPAN>My fiancée and I have two dogs that came from a shelter, and we always wondered where they came from and what was their history before they came to us.<SPAN>&nbsp; </SPAN>I thought the concept of a foster home could easily apply to Imaginary Friends.<SPAN>&nbsp; </SPAN>They would have been created by a certain kid, lived a certain life and then given up for one reason or another so they had this history.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>And unlike <I>The Powerpuff Girls,</I> I didn’t have to worry about good guys and bad guys and saving the day.<SPAN>&nbsp; </SPAN>In every<I> Powerpuff Girls</I> episode you had this built in agenda: a crime, a villain and saving the day.<SPAN>&nbsp; </SPAN>With this new concept, I wanted something where I could have the smallest germ of an idea and just spin off into characters and comedy.</SPAN></P>
<P><SPAN>There are a lot of shows out there today with aggressiveness, an us vs. them approach, and fighting.<SPAN>&nbsp; </SPAN>I was seeing a lack of shows that were just about characters hanging out and telling stories.<SPAN>&nbsp; </SPAN>I remember watching <I>SpongeBob</I> and thinking that it was refreshing to watch a comedy series about funny characters.<SPAN>&nbsp; </SPAN>I thought I’d like to get back to doing that kind of storytelling and do that type of a show.<SPAN>&nbsp; </SPAN><I>Foster’s</I> is a perfect vehicle for that, where I can just let the characters drive the story.<SPAN>&nbsp; </SPAN>It’s about the personalities of these characters, how they relate to one another and putting them in situations and seeing how they would deal with it.<SPAN>&nbsp; </SPAN>It’s really freeing from that standpoint.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>What was the first character you created?</SPAN></B></P>
<P><SPAN>Blooregard was the first specific Imaginary Friend I created.<SPAN>&nbsp; </SPAN>I had created a very different version of <I>Foster’s</I> and realized it wasn’t going in the direction I had hoped, so I quickly changed the dynamics and turned it into a foster home.<SPAN>&nbsp; </SPAN>Many of the characters from my initial show idea were able to move over after I simplified the show idea.<SPAN>&nbsp; </SPAN></SPAN><SPAN><BR></SPAN></P>
<P><SPAN>The concept was always about Imaginary Friends mixing with real people: Creating weird bizarre characters and juxtaposing them with normal people.<SPAN>&nbsp; </SPAN>And then putting them all in everyday situations like eating dinner or cleaning up.<SPAN>&nbsp; </SPAN>I wanted real, basic, day-to-day living situations to add Imaginary Friends to the mix!<SPAN>&nbsp; </SPAN>I really like that contrast.<SPAN>&nbsp; </SPAN>Some of the humor of the show is subtle, but there is something funny about a 22-year-old girl getting into serious arguments with a 7-foot-tall rabbit in a tuxedo.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>How is making <I>Foster’s</I> different than <I>The Powerpuff Girls</I>?</SPAN></B></P>
<P><SPAN>With <I>Foster’s</I> we are writing scripts on this show (as opposed to beginning with storyboards on <I>The Powerpuff Girls</I>), because the show is 22 minutes long and every episode is story-driven.<SPAN>&nbsp; </SPAN>We also want to make sure that every one of the characters gets the right amount of screen time, the pacing is correct, we have the right build and each character has the right voice.<SPAN>&nbsp; </SPAN>It’s easier to make changes to a script than it is to a finished, drawn storyboard.<SPAN>&nbsp;&nbsp; </SPAN>It takes so long to storyboard that you feel bad making changes to it.<SPAN>&nbsp; </SPAN>It’s much easier to shape and form a script and prepare it before you go to the board stage.<SPAN>&nbsp; </SPAN>It gives me more control of the story so I can make sure it’s just the way I want it.<SPAN>&nbsp; </SPAN>Once the script is done, I feel confident it’s going to turn into a good board.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>How has the longer length affected your storytelling?</SPAN></B></P>
<P><SPAN>It gives us more room for “business,” which is when the characters are just doing funny stuff.<SPAN>&nbsp; </SPAN>We use “business” to propel the story forward, but it’s never a major plot point.<SPAN>&nbsp; </SPAN>In an 11-minute show, you only have a 3-5-minute story so you have enough time for “business.” But a 3-minute story is pretty simple.<SPAN>&nbsp; </SPAN>With a 22-minute episode, I can tell an 8-10 minute story and still have plenty of room for “business.”<SPAN>&nbsp; </SPAN>With this format, there’s time for characters to be funny and be themselves and tell a good, meaty story.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>You are using an exciting new production process on <I>Foster’s</I>.<SPAN>&nbsp; </SPAN>Please describe.</SPAN></B></P>
<P><SPAN>It’s a digital/2-D hybrid production process.<SPAN>&nbsp; </SPAN>Our artwork starts out hand-drawn on paper as usual, and then the characters and backgrounds are cleaned up in the Illustrator program, which means it is vector-based art.<SPAN>&nbsp; </SPAN>Then we can take it into Flash, which allows the characters to be broken up and composited in After Effects.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>The entire process basically affords us a look we could never get before.<SPAN>&nbsp; </SPAN>It also lets us re-use material; every time we create a walk cycle for a character, we can re-use it and you never have to animate it again.<SPAN>&nbsp; </SPAN>So it’s much more efficient and the more shows we do, the more of a library we build and the quicker we can animate each show.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>We are the first people to be putting all these elements together.<SPAN>&nbsp; </SPAN>They’ve all been used separately, but using these programs the way we do is completely new.<SPAN>&nbsp; </SPAN>We are applying a traditional hand-drawn animation philosophy to these new technologies. A lot of people tend to use Flash and let the software do the work for the animator, and we are not.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>We’re treating the animation as if it were being created by hand.<SPAN>&nbsp; </SPAN>We are making the software work better for an animator but not relying on the technology to do the work for us but use it in assisting us.<SPAN>&nbsp; </SPAN>So now, it looks like it would if we were animating it by hand.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Another benefit is that, because all our animators are using all the same assets, there is never any concern about a show being off-model.<SPAN>&nbsp; </SPAN>In traditional animation you never know what overseas crew is going to get your show:<SPAN>&nbsp; </SPAN>Is it an A crew or a B crew?<SPAN>&nbsp; </SPAN>Do they have a strong artist or weak one?<SPAN>&nbsp; </SPAN>It’s always a gamble as to what your show is going to come back looking like, and, with this process, we never have to worry.</SPAN></P>
<P><SPAN>And because the artwork is vector-based, we can zoom in and out without losing any of the integrity of the backgrounds or character art, which sometimes happens with hand-drawn animation.<SPAN>&nbsp; </SPAN>We also have a lot more options in terms of the camera work we can do.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Can you talk about the different look of <I>Foster’s</I> as compared to <I>The Powerpuff Girls</I>?</SPAN></B></P>
<P><SPAN>I created the big, black outlines of <I>The Powerpuff Girls</I> during a time when I was really into graphic design.<SPAN>&nbsp; </SPAN>At the time we started <I>The Powerpuff Girls</I>, there weren’t a lot of shows out there with that look.<SPAN>&nbsp; </SPAN>I wanted to make cartoons look cool and “design-y” again.<SPAN>&nbsp; </SPAN>We did that, and, over the past few years, the fat black line has become the default look of kids” cartoons and it’s not as impactful anymore.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>When we created this new production process for <I>Foster’s,</I> we realized we can make it look anyway we wanted to.<SPAN>&nbsp; </SPAN>We thought “Wouldn’t it be cool to give the character texture and show a brush stroke or a loose brush line to make it look more organic?”<SPAN>&nbsp; </SPAN>New technology has given us many more options with how to make the show look, so why stick to the same thing?<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>But the style of the show is just a creative choice.<SPAN>&nbsp; </SPAN>What drives the show is the characters and the story.<SPAN>&nbsp; </SPAN>From there, you can design a show to look any way.<SPAN>&nbsp; </SPAN>As long as the characters and story are strong, the design is the icing on the cake. </SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>What role does music have in <I>Foster’s</I>?</SPAN></B></P>
<P><SPAN>The music is always a huge part of storytelling.<SPAN>&nbsp; </SPAN>It became a character in <I>The Powerpuff Girls</I> and acted as a voice of the characters.<SPAN>&nbsp; </SPAN>Because the house in <I>Foster’s</I> is Victorian and because I’m a huge ‘6os psychedelic music fan, I went to our composer, Jim Venable (who worked on <I>The Powerpuff Girls</I> and <I>Samurai Jack</I>), and said “Let’s try to do psychedelic ragtime.”<SPAN>&nbsp; </SPAN>We combined psychedelic player pianos, mellotron and antique sounds with a weird ‘60s vibe to give the music a surreal, magical sound.<SPAN>&nbsp; </SPAN>The theme music is catchy, quick and energetic and it enlivens the show and takes it up another level.<SPAN>&nbsp; </SPAN>The show is great and funny by itself, but, when you add the music, the level of excitement, fun and pace is greatly enhanced.</SPAN></P>
<P><B><SPAN></SPAN></B>&nbsp;</P>
<P><B><SPAN>What traits do you share with your leads, Mac and Blooregard?</SPAN></B></P>
<P><SPAN>Blooregard is a lot more like I was as a little kid:<SPAN>&nbsp; </SPAN>I was the center of attention, the youngest child in my family, the showman.<SPAN>&nbsp; </SPAN>Mac is more like me now:<SPAN>&nbsp; </SPAN>aware of others’ feelings, quiet, shy, sensitive.<SPAN>&nbsp; </SPAN>Mac also seems to look like me as a little kid, which was unintentional, but it just happened that way!</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>How is the house a character in the show?</SPAN></B></P>
<P><SPAN>For every show I’ve created, there has been one visual that represents the show.<SPAN>&nbsp; </SPAN>In <I>The Powerpuff Girls</I>, it was this cute little iconic character punching a giant monster; it was that contrast that was interesting.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>With <I>Foster’s</I> it was this ornate Victorian sitting room with couches with these weird psychedelic characters sitting on them.<SPAN>&nbsp; </SPAN>That image is what became the show in my mind: That cool contrast of these bizarre characters being in this weird out-of-time environment.<SPAN>&nbsp; </SPAN>Making the main setting a Victorian mansion makes it more of a cool place you’d want to go to than, say, an apartment building.<SPAN>&nbsp; </SPAN>It’s visually more interesting.<SPAN>&nbsp; </SPAN>Kids can’t really relate to it, so it makes it more magical.<SPAN>&nbsp; </SPAN>Also, Victorian mansions are really big, with lots of rooms with mysterious stairways and rooms and hallways, they can be an endless source of imagination and environment.<SPAN>&nbsp; </SPAN>Whatever we create can exist in this house.<SPAN>&nbsp;&nbsp; </SPAN></SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Frankie seems so normal and grounded.<SPAN>&nbsp; </SPAN>Is she inspired by anyone?</SPAN></B></P>
<P><SPAN>Frankie is pretty much inspired by my fiancée, Lauren.<SPAN>&nbsp; </SPAN>She’s a strong, independent woman who believes in doing the right thing. </SPAN></P>
<P><SPAN>Frankie is someone who really believes in what the house represents and cares about the Imaginary Friends.<SPAN>&nbsp;&nbsp; </SPAN>She hates having to do all the grunt work and daily tasks, but she believes so strongly in the cause that she continues.<SPAN>&nbsp; </SPAN>She’s the big sister to all the friends in the house.<SPAN>&nbsp; </SPAN>People look up to her.<SPAN>&nbsp; </SPAN>She’s the contrast and connection to normal daily life.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Is Blooregard the kind of character Mac wishes him to be?</SPAN></B></P>
<P><SPAN>Mac and Blooregard balance each other out.<SPAN>&nbsp; </SPAN>Blooregard does the things Mac wishes he could do if he wasn’t so shy.<SPAN>&nbsp; </SPAN>Blooregard needs Mac because without him he would destroy the world and couldn’t control himself.<SPAN>&nbsp; </SPAN>They are part of the same person because Mac created Blooregard from his mind – together they are almost one whole character.</SPAN><B><SPAN>&nbsp;</SPAN></B></P>
<P><B><SPAN></SPAN></B>&nbsp;</P>
<P><B><SPAN>You work with a number of voice actors from <I>The Powerpuff Girls</I>.<SPAN>&nbsp; </SPAN>Did you create characters with certain actors in mind?</SPAN></B></P>
<P><SPAN>The concept for all the characters voices were always there and I auditioned many of the same people I had worked with before, and, lo and behold, they were the best people!<SPAN>&nbsp; </SPAN>We were looking for more than a funny voice </SPAN><FONT size=+0>– </FONT><SPAN>we wanted someone who was a great performer and someone who embodied the character and his spirit.<SPAN>&nbsp; </SPAN>For example, after auditioning many people who had perfect Spanish for the character of Eduardo, Tom Kenny, who I’ve worked with for years, came in and did this kind of awkward, childish, “Cookie Monster-ish” voice that embodied the spirit of Eduardo.<SPAN>&nbsp; </SPAN>Even though his Spanish wasn’t so dead on, he had the spirit of the character and got the part!</SPAN></P>
<P><SPAN>Blooregard was the hardest voice to find. I had something so specific but intangible in mind.<SPAN>&nbsp; </SPAN>Because Blooregard can be a bit of a jerk sometimes, I didn’t want an annoying or grating voice but I wanted an excited innocence.<SPAN>&nbsp; </SPAN>I needed an Owen Wilson type </SPAN><FONT size=+0>–</FONT><SPAN> he plays loveable bad guys.<SPAN>&nbsp; </SPAN>We auditioned so many people without success, and, on the last day, Keith Ferguson came in and nailed it.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>When you were pitching this show did you do any research on Imaginary Friends?</SPAN></B></P>
<P><SPAN>I asked myself the reasons a kid would create an Imaginary Friend.<SPAN>&nbsp; </SPAN>They would create a friend who would be a protector, a companion to hang out with, a friend out of loneliness or a scapegoat to blame everything on.<SPAN>&nbsp; </SPAN>So by taking those basic motivations, we then created many of the characters.<SPAN>&nbsp; </SPAN>Eduardo is the protector, Coco is the one to keep you company, Blooregard is the best friend to pal around with and Wilt is the guy to have fun and play sports with.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Coming up with the basic motivations why kids would create imaginary friends gave me a start for the main characters.<SPAN>&nbsp; </SPAN>I also incorporated imaginary friends that came from different time periods.<SPAN>&nbsp; </SPAN>For example, Mr. Herriman, is a proper imaginary friend from an earlier era.<SPAN>&nbsp; </SPAN>Wilt is a basketball player from the mid ‘70s, so that’s why he looks this way.</SPAN></P>
<P><SPAN>And then I took all these archetypes of Imaginary Friends and applied them to the types of dogs you find in a shelter: the hyper dog, the untrained dog, the three-legged dog, the guard dog.<SPAN>&nbsp; </SPAN>That led me to help create each character’s personality.</SPAN></P>
<P><SPAN><SPAN></SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Did you have an imaginary friend?<SPAN>&nbsp; </SPAN>Do you wish you did?<SPAN>&nbsp; </SPAN>What would it have been like?</SPAN></B></P>
<P><SPAN>No, I didn’t have a specific Imaginary Friend.<SPAN>&nbsp; </SPAN>I have always talked to myself, even as a little kid, so technically I probably do have someone I’m speaking to, but it’s never taken a specific form or shape.<SPAN>&nbsp; </SPAN>Maybe I’m talking to the other side of myself?</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P><br>Source: Cartoon Network Pressroom (Now defunct)</span>
<?php include "../footer.html"; ?>