<?php include("../header.php"); ?>
<P><FONT size=4>Glen Murakami Talks About His Work on Teen Titans</FONT></P><STRONG>What types of stories are you trying to tell?</STRONG> 
<P>We’re trying to tell stories that kids can relate to – by using problems that real teenagers have.<SPAN>&nbsp;&nbsp; </SPAN>For example, we’ll deal with things like sibling rivalry and bullying, but not in an “after school special” kind of way.<SPAN>&nbsp; </SPAN>Our take is that the Teen Titans are real kids who just happen to have superpowers.<SPAN>&nbsp; </SPAN></P>
<P><SPAN></SPAN><STRONG></STRONG>&nbsp;</P>
<P><STRONG>What does each character bring to the group?</STRONG> </P>
<P>Robin is the leader – the brains of the operation.<SPAN>&nbsp; </SPAN>Cyborg is the backbone; he provides strength to the group – physically and emotionally.<SPAN>&nbsp; </SPAN>Beast Boy is the humor.<SPAN>&nbsp; </SPAN>Starfire is the positive energy of the group.<SPAN>&nbsp; </SPAN>Raven is not exactly a pessimist, but she definitely provides balance.</P>
<P>When we started creating the show, the first question we asked was: “What are the characters’ flaws?”<SPAN>&nbsp; </SPAN>Once we knew what the characters’ limitations were, we knew how to play them off one another.<SPAN>&nbsp; </SPAN>As a result, all the characters are funny.<SPAN>&nbsp; </SPAN>It’s not like we said that Beast Boy is the funny one and he’s the only one who cracks jokes.<SPAN>&nbsp; </SPAN>They’re all funny, but it’s within their own character.<SPAN>&nbsp;&nbsp; </SPAN>Playing the characters against each other is where you get the conflict and the humor. </P>
<P>&nbsp;</P>
<P><STRONG>What are some of your influences for the show?</STRONG></P>
<P>Animé has been a big influence on the show - everything from <I>Speed Racer</I> and <I>Kimba the White Lion</I> to the work of creators like Osamu Tezuka, Ishinomori Shotaro and Hiyao Miyazaki.<SPAN>&nbsp; </SPAN>The series <I>FLCL</I> was a major influence.<SPAN>&nbsp; </SPAN></P>
<P>I’m from a generation that grew up watching animé shows like <I>Battle of the Planets</I> and <I>G-Force</I>.<SPAN>&nbsp; </SPAN>I think my generation, and the kids growing up today, will be familiar with some of the style and techniques we’ll be bringing to U.S audiences on <I>Teen Titans</I>.</P>
<P>Having worked on series like <I>Superman</I>, <I>Batman: The Animated Series</I>, <I>Batman Beyond </I>and <I>Justice League</I>, it gave me a clear example of what had been done in this genre, and that we were going to try to move in a different direction.</P>
<P>Illustrators like Bob Peak and Coby Whitmore have been big influences on the loose, painterly style we have been using for the backgrounds.<SPAN>&nbsp; </SPAN>And our story editor, David Slack, has referred the show as a superhero version of <I>The Breakfast Club</I>.<SPAN>&nbsp; </SPAN>There’s some truth in that.</P>
<P>&nbsp;</P>
<P><B>How will you balance the “Teen” with the “Titans”?<SPAN>&nbsp; </SPAN>What types of “teen issues” will they confront?</B></P>
<P>Every good story is what its metaphor should be.<SPAN>&nbsp; </SPAN>Instead of getting very specific, we tend to choose stories that everyone can relate to.<SPAN>&nbsp; </SPAN>We think that everyone can relate to being bullied.<SPAN>&nbsp; </SPAN>You don’t have to be a superhero or a robot hybrid to know what that feels like.<SPAN>&nbsp; </SPAN>Same thing with sibling rivalry – it’s a universal problem.<SPAN>&nbsp; </SPAN></P>
<P>We make the show fun, though, and it’s about superheroes doing their thing.<SPAN>&nbsp; </SPAN>And that’s how it avoids becoming an after-school special.<SPAN>&nbsp; </SPAN>We’re not hitting the audience over the head with anything.<SPAN>&nbsp; </SPAN></P>
<P>&nbsp;</P><B><SPAN><BR></SPAN></B>
<P><B>How does<SPAN>&nbsp; </SPAN><I>Teen Titans</I> compare with other animated shows?<SPAN>&nbsp; </SPAN>What about the music?</B></P>
<P>The look of <I>Teen Titans</I> is different than any other superhero show created for an American or western market because no other show has been so heavily influenced by animé.<SPAN>&nbsp; </SPAN>We use some “super-deformed” kind of takes, which I think of as a Japanese equivalent to a Tex Avery approach.<SPAN>&nbsp; </SPAN></P>
<P>The fact that there is such a strong element of humor in <I>Teen Titans</I> makes it different than most superhero shows.<SPAN>&nbsp; </SPAN>But our humor is not ironic at all – we’re not mocking our characters, we’re just incorporating humor into their interaction, keeping it true to the way that real teens would react.</P>
<P>Musically in <I>Teen Titans</I>, we’re doing anything and everything that is appropriate for the feel of the show.<SPAN>&nbsp; </SPAN>The music will vary, in some cases, for every show or even within a specific show.<SPAN>&nbsp; </SPAN>One time it might be jazzy lounge music, and, in another, it will be techno, to help with the mood or feel of the show.<SPAN>&nbsp; </SPAN>I don’t feel like this show will ever be traditional musically in the way we were with <I>Batman</I> or <I>Superman</I>.</P>
<P><SPAN></SPAN><B></B>&nbsp;</P>
<P><B>You’ve worked on other shows with superheroes – how is <I>Teen Titans</I> different?</B></P>
<P><I>Batman</I>, <I>Superman</I> and <I>Justice League</I> broke new ground.<SPAN>&nbsp; </SPAN>No one ever tried to portray superheroes in that way before.<SPAN>&nbsp; </SPAN>The style of storytelling was more realistic, more filmic.<SPAN>&nbsp; </SPAN>We took a comic book story and told it in the style of a movie.<SPAN>&nbsp; </SPAN></P>
<P>With <I>Teen Titans</I>, we went back a step and made it more like a traditional cartoon.<SPAN>&nbsp;&nbsp; </SPAN>Also, <I>Teen Titans</I> will be more character driven.<SPAN>&nbsp; </SPAN>As in old <I>Star Trek</I> episodes, these characters are iconic in their own way, even though the audience may not be familiar with their history in the comics.<SPAN>&nbsp; </SPAN>The humor and tension comes out by contrasting these types against each other. </P>&nbsp; 
<P><B>How is Robin in <I>Teen Titans</I> different from the Robin we’ve seen in Batman?</B></P><SPAN>In <I>Teen Titans</I>, we don’t even really think of Robin as part of the “Batman and ….” team.<SPAN>&nbsp; </SPAN>I’m trying to treat him as a brand new character that people have never seen before.<SPAN>&nbsp; </SPAN>He’s the leader instead of the sidekick.<SPAN>&nbsp; </SPAN>He’s independent.<SPAN>&nbsp; </SPAN>He’s not in the shadow of his father figure, nor is he going to react in the same way Batman might. In fact, we’ll never mention Batman at all in the series.<SPAN>&nbsp; </SPAN></SPAN>&nbsp; How closely will the TV series stick to the popular DC Comics series? 
<P>We’ve looked through the entire history of the characters – from the very beginning – and tried to boil all of it down and condense it.<SPAN>&nbsp; </SPAN>We’ve tried to take the best parts of each character through the years.<SPAN>&nbsp; </SPAN>Things have changed – like the costumes and the character design, but not so much that a comic fan would not recognize them.<SPAN>&nbsp; </SPAN>But the show will remain an entity unto itself.<SPAN>&nbsp; </SPAN></P>
<P>We’ve focused on telling the story of the characters rather than dwelling on their backstory.<SPAN>&nbsp; </SPAN>This is a show about the characters trying to find out things about themselves.<SPAN>&nbsp; </SPAN>Throughout the course of the series, it will touch on where the characters come from, but we won’t be doing flashbacks.<SPAN>&nbsp; </SPAN>We try to create situations where the rest of the Teen Titans learn about one of the team members, in the way any real kid would.<SPAN>&nbsp; </SPAN></P>
<P>When I was a kid, I didn’t get caught up in origin stories too much.<SPAN>&nbsp; </SPAN>You never questioned why the Three Stooges had different jobs all the time or how Speed Racer got to drive the car.<SPAN>&nbsp; </SPAN>They just did.<SPAN>&nbsp; </SPAN>Once the story gets going, you get so involved that the backstory just did not seem that important.<SPAN>&nbsp; </SPAN></P>
<P><B></B>&nbsp;</P>
<P><B>What kind of audience do you expect <I>Teen Titans</I> to attract? </B></P>
<P>I think everyone will like it.<SPAN>&nbsp; </SPAN>The stories work on so many different levels.<SPAN>&nbsp; </SPAN>If you want action, there’s action.<SPAN>&nbsp; </SPAN>If you want humor, there is humor.<SPAN>&nbsp;&nbsp; </SPAN>But all the stories are very strong and they are actually <I>about </I>something.<SPAN>&nbsp; </SPAN>They’re about how people feel and I think everyone will be able to relate to that.<SPAN>&nbsp; </SPAN>The Teen Titans are superheroes, but their problems are not so far above the problems of anyone watching that they will not be able to relate to it.<SPAN>&nbsp; </SPAN>The villains, in many ways, are about helping the characters learn more about themselves.<SPAN>&nbsp; </SPAN></P><br>Source: Cartoon Netork Pressroom (Now defunct)</span>
<?php include "../footer.html"; ?>