<?php include("../header.php"); ?>
<P><FONT size=4>Joe Murray Talks About His Work On Camp Lazlo</FONT></P>
<P><B><SPAN>Q:<SPAN>&nbsp; </SPAN>Why did you decide on a camp setting for your new series, <I>Camp Lazlo</I>?</SPAN></B></P>
<P><SPAN>A:<SPAN>&nbsp; </SPAN>After I did <I>Rocko’s Modern Life</I>, I kept this notebook full of ideas for shows or books.<SPAN>&nbsp; </SPAN>Some of my best memories were always at camp, and I just kept coming back to that.<SPAN>&nbsp; </SPAN>I was going through a period of time where I was feeling that there were too many futuristic things going on in media and entertainment, so I wanted to do something that really got back to nature.<SPAN>&nbsp; </SPAN>I remember watching cartoons like Yogi Bear and Bugs Bunny where there were all these trees in the background.<SPAN>&nbsp; </SPAN>There’s some sort of calming about that.<SPAN>&nbsp; </SPAN>I wanted to create a place without any Gameboys or televisions around so the characters could have a good time and just be kids.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q:<SPAN>&nbsp; </SPAN>How long did you go to camp?<SPAN>&nbsp; </SPAN>Did your success as a camper, or lack of it, influence the show?</SPAN></B></P>
<P><SPAN>A:<SPAN>&nbsp; </SPAN>I went every summer for 4 or 5 years in a row.<SPAN>&nbsp; </SPAN>But I couldn’t really get the scouting thing down.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q:<SPAN>&nbsp; </SPAN>So is this your idealized version of what a camp would be?</SPAN></B></P>
<P><SPAN>A:<SPAN>&nbsp; </SPAN>I think there are a lot of aspects to what <I>Camp Lazlo</I> represents.<SPAN>&nbsp; </SPAN>It’s kind of a goofy place, but the most important thing that it showcases is friendship.<SPAN>&nbsp; </SPAN>Whether they are arguing with each other or just hanging around, the people there are what make camp fun.<SPAN>&nbsp; </SPAN>I’d like to hang out with Raj or Clam or Lazlo; they’re my kind of people, even if they actually are animals.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q:<SPAN>&nbsp; </SPAN>Were you like Lazlo as a kid?</SPAN></B></P>
<P><SPAN>A:<SPAN>&nbsp; </SPAN>I think there is a lot of good-natured rebelliousness in me.<SPAN>&nbsp; </SPAN>I was always questioning authority and why we had to do certain things.<SPAN>&nbsp; </SPAN>I always felt that if someone wanted to do something, they should go ahead and do it.<SPAN>&nbsp; </SPAN>In that sense, I was a lot like Lazlo.<SPAN>&nbsp; </SPAN>I don’t think I was as happy or easy-going as Lazlo.<SPAN>&nbsp; </SPAN>I was a little bit more moody.<SPAN>&nbsp; </SPAN>I still am.<SPAN>&nbsp; </SPAN>I admire the way Lazlo can make the best of situations when things go against him.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><SPAN><STRONG>Q:<SPAN>&nbsp; </SPAN>Camp Kidney is very structured.<SPAN>&nbsp; </SPAN>Lazlo doesn’t like structure.<SPAN>&nbsp; </SPAN>What’s the message for the kids?</STRONG></SPAN></P>
<P><SPAN>A:<SPAN>&nbsp; </SPAN>{laughing} I try not to send messages to “the kids.”<SPAN>&nbsp; </SPAN>I don’t think cartoons are the place for messages.<SPAN>&nbsp; </SPAN>And I hope that there are not too many messages to be soaked in by watching <I>Camp Lazlo</I>.<SPAN>&nbsp; </SPAN>My main thing is “be who you are.”<SPAN>&nbsp; </SPAN>Sometimes, there are going to be situations where people are going try to tell you what to do.<SPAN>&nbsp; </SPAN>And, unless it’s a safety issue, feel free to question it.<SPAN>&nbsp; </SPAN>Be a kid.<SPAN>&nbsp; </SPAN>I think growing up is mostly about making decisions about what is right and wrong for you.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><SPAN><STRONG>Q:<SPAN>&nbsp; </SPAN>You are working with a lot of the same cast and crew as you did on <I>Rocko’s Modern Life</I>.<SPAN>&nbsp; </SPAN>How did you get them to join <I>Camp Lazlo</I>?</STRONG></SPAN></P>
<P><SPAN>A:<SPAN>&nbsp; </SPAN>Coercion.<SPAN>&nbsp; </SPAN>We had a really good time on <I>Rocko</I>.<SPAN>&nbsp; </SPAN>We always kept in touch and they told me to look them up if I ever did another project.<SPAN>&nbsp; </SPAN>And I knew what they could deliver.<SPAN>&nbsp; </SPAN>Mark O’Hare, my <SPAN>co-producer</SPAN>, is so consistent and so amazing in the way he can write and draw.<SPAN>&nbsp; </SPAN>And he’s a great person.<SPAN>&nbsp; </SPAN>And this crew already knows my sensibilities, only now they have another 10 years worth of experience.<SPAN>&nbsp; </SPAN>Many of them worked on <I>SpongeBob SquarePants </I>after <I>Rocko’s Modern Life</I>, so they learned a lot there.<SPAN>&nbsp; </SPAN>Plus, we have some new people working on the show, and they bring great enthusiasm in.<SPAN>&nbsp; </SPAN>It’s an incredible crew.<SPAN>&nbsp; </SPAN>We’re very lucky.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><SPAN><STRONG>Q:<SPAN>&nbsp; </SPAN>You also have much of the same voice talent from <I>Rocko’s Modern Life</I>.<SPAN>&nbsp; </SPAN>How did you decide to cast them for each of their roles?</STRONG></SPAN></P>
<P><SPAN>A:<SPAN>&nbsp; </SPAN>I knew I wanted to work with Tom Kenny.<SPAN>&nbsp; </SPAN>He adds writing to his roles; he brings so much.<SPAN>&nbsp; </SPAN>Other than that, I didn’t know who I wanted for voices.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Carlos Alazraqui ended up being Lazlo, just like he was Rocko.<SPAN>&nbsp; </SPAN>I don’t know how that happened.<SPAN>&nbsp; </SPAN>I really didn’t plan on it.<SPAN>&nbsp; </SPAN>And Doug Lawrence was on <I>Rocko’s Modern Life</I> and now he’s Edward and The Loons.</SPAN></P></DIV>
<P><SPAN>But we’ve got some new people.<SPAN>&nbsp; </SPAN>Jeff Glen Bennett does Raj.<SPAN>&nbsp; </SPAN>He’s incredible.<SPAN>&nbsp; </SPAN>Steve Little, who voices the Dung Beetles, is on his first voice-acting job.<SPAN>&nbsp; </SPAN>I got him from The Groundlings.<SPAN>&nbsp; </SPAN>So it’s a good mix.</SPAN></P>
<P><FONT size=2>The thing I look for from all my voice talent is comedic timing.<SPAN>&nbsp; </SPAN>Most of them are stand-up comics or sketch actors.<SPAN>&nbsp; </SPAN>And improv actors – they not only have great voices, but they bring a lot of improvisational comedy to their recording sessions.<SPAN>&nbsp; </SPAN>Since we record as an ensemble, they feel the need to make each other laugh.</FONT></P>
<P><SPAN>I’m working with Jeff Hutchins who used to cut the sound effects for <I>Rocko</I> to do the sound for <I>Camp Lazlo</I>.<SPAN>&nbsp; </SPAN>And it turns out that I am picking the same exact sounds as I picked 10 years ago.<SPAN>&nbsp; </SPAN>So it seems that what I look for when I tell my stories is just sort of ingrained in me.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><SPAN><STRONG>Q:<SPAN>&nbsp; </SPAN>What lessons did you learn from making your first series that you have applied to <I>Camp Lazlo</I>?</STRONG></SPAN></P>
<P><SPAN>A:<SPAN>&nbsp; </SPAN>When I made <I>Rocko</I>, I was used to making my own films and doing every little aspect of the film.<SPAN>&nbsp; </SPAN>When I got into TV, I tried that approach and it was driving me crazy.<SPAN>&nbsp; </SPAN>And so I started to let a lot of things be handled by people who were good at handling them and not try to do every aspect of every job.</SPAN></P>
<P><SPAN>We were doing things that made us laugh, so I think <I>Rocko</I> skewed kind of older.<SPAN>&nbsp; </SPAN>Now, I have kids of my own, and I know what is funny with kids as well as adults.<SPAN>&nbsp; </SPAN>It’s got a broader appeal, but it’s also something I personally find is funny.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>I still approve everything but I try to resist the urge to noodle in every little detail.<SPAN>&nbsp; </SPAN>On <I>Camp Lazlo</I>, we had a lot of pre-production time, so we were able to set everything up in advance and hand it over to the artists and the crew.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q:<SPAN>&nbsp; </SPAN>How has being a father helped shape the creation of <I>Camp Lazlo</I>?</SPAN></B><SPAN></SPAN></P>
<P><FONT size=2>A:<SPAN>&nbsp; </SPAN>It has allowed me to see things from the perspective of a child.<SPAN>&nbsp; </SPAN>I think we lose that as we get older.<SPAN>&nbsp; </SPAN>And when I play with my daughters, I realize that it all comes down to imagination.<SPAN>&nbsp; </SPAN>You can create total worlds.<SPAN>&nbsp; </SPAN></FONT></P>
<P><SPAN>When we have challenges and conflicts as a family, I think it helps when we approach it with imagination. <SPAN>&nbsp;</SPAN>So I started bringing that to <I>Camp Lazlo</I>.<SPAN>&nbsp; </SPAN>Lazlo deals with his challenges and problems with imagination.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>Sometimes, I’ll get hung up on an idea during the day.<SPAN>&nbsp; </SPAN>And then I’ll come home to my girls and somehow the answers just come to me.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>We were trying to come up with a song for a luau scene and nothing we came up with was working.<SPAN>&nbsp; </SPAN>Then I went home and my daughter started singing “The Hokey Pokey.”<SPAN>&nbsp; </SPAN>So I came up with “The Hula Pokey” and made up stuff about throwing poi.<SPAN>&nbsp; </SPAN>It made her laugh, so we decided to use it.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q:<SPAN>&nbsp; </SPAN>Will there be a lot of music and camp songs in the show?</SPAN></B></P>
<P><SPAN>A:<SPAN>&nbsp; </SPAN>Well, the theme song is based on “Bingo,” which I used to sing at camp.<SPAN>&nbsp; </SPAN>So we switched that to “L-A-Z-L-O.”<SPAN>&nbsp; </SPAN>We’re re-making a lot of songs for the show.<SPAN>&nbsp; </SPAN>And we’re also writing our own camp songs.<SPAN>&nbsp; </SPAN>So there’s a lot of music.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>And Andy Paley, who is an incredible musician, created a whole bunch of original bluegrass and cowboy swing for the show.<SPAN>&nbsp; </SPAN>We used all kinds of strange instruments, washboards and spoons.<SPAN>&nbsp; </SPAN>There was this woman who played the saw.<SPAN>&nbsp; </SPAN>So we have some original songs that Andy wrote as well as old favorites like “She’ll Be Coming Around the Mountain” that we reworked.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q:<SPAN>&nbsp; </SPAN>How did you select which types of animal the campers would be?</SPAN></B></P>
<P><SPAN>A:<SPAN>&nbsp; </SPAN>I tried to use the same approach as I used in <I>Rocko</I>, where it was a sort of a social caricature.<SPAN>&nbsp; </SPAN>I was trying the match the personality of the character to various animals.<SPAN>&nbsp; </SPAN>When I started thinking about the personality of Lazlo, a monkey just came to mind.<SPAN>&nbsp; </SPAN>Not like a chimpanzee, but a Brazilian spider monkey, which is what he is.<SPAN>&nbsp; </SPAN>And I thought of an Indian elephant and what his personality might be, that’s how we got Raj.<SPAN>&nbsp; </SPAN>And Clam… I have no idea where he came from.<SPAN>&nbsp; </SPAN>I just started drawing this character and then I put rhino horns on him…. so that’s what he became.</SPAN></P>
<P><SPAN>Every character has been thought out.<SPAN>&nbsp; </SPAN>Edward the Platypus, the Dung Beetles, Samson the Guinea Pig, the Lemmings… their personalities all match what they are.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q:<SPAN>&nbsp; </SPAN>The color palette and art direction are interesting and beautiful.<SPAN>&nbsp; </SPAN>How did they develop?</SPAN></B></P>
<P><FONT size=2>A:<SPAN>&nbsp; </SPAN>I looked through a lot of books on cabins and camps and Indian artifacts.<SPAN>&nbsp; </SPAN>They’re all pulled from various artifacts, like rugs and totem poles.<SPAN>&nbsp; </SPAN>And we use a lot of nature colors – dark greens, oranges and reds.<SPAN>&nbsp;&nbsp; </SPAN></FONT></P>
<P><SPAN>My art director, Sue Mondt, and I were trying to find colors that would reflect the feeling you had in summer at camp, but they did not have be so specific.<SPAN>&nbsp; </SPAN>A tree does not always have to be green and brown.<SPAN>&nbsp; </SPAN>The sky is yellow.<SPAN>&nbsp; </SPAN>We try and get away from the normal colors of things.<SPAN>&nbsp; </SPAN>You have a definite feeling you are in a different place.<SPAN>&nbsp; </SPAN>But most of our choices are about triggering your memory of camp and being in the woods.</SPAN></P>
<P><SPAN>There is a definite retro feel to the camp’s design.<SPAN>&nbsp; </SPAN>I’m a big fan of ‘50s and early ‘60s design – advertising art, lamps, old vacation brochures and things like that.<SPAN>&nbsp; </SPAN>The brushy quality that developed at that time was a real influence.<SPAN>&nbsp; </SPAN>It’s all meant to evoke a comfortable place to visit.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q:<SPAN>&nbsp; </SPAN>What were your inspirations on the show – animation and beyond?</SPAN></B></P>
<P><SPAN>A:<SPAN>&nbsp; </SPAN>I am a huge fan of storybook art.<SPAN>&nbsp; </SPAN>That’s always been an inspiration for me.<SPAN>&nbsp; </SPAN>And then painters like Matisse and Picasso.<SPAN>&nbsp; </SPAN>And great comic strip artists are very important to both Mark O’Hare and me.<SPAN>&nbsp; </SPAN>Music – cowboy swing and other old stuff – has been influential to the show.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q:<SPAN>&nbsp; </SPAN>Finally, can a monkey and a mongoose really find true love?</SPAN></B></P>
<P><SPAN>A:<SPAN>&nbsp; </SPAN>Wow.<SPAN>&nbsp; </SPAN>We’re going to have to find that out.<SPAN>&nbsp; </SPAN>It’s hard to say.<SPAN>&nbsp; </SPAN>Lazlo is a little freaked out by Patsy.<SPAN>&nbsp; </SPAN>She scares him.<SPAN>&nbsp; </SPAN>I think Patsy will always be a little more aggressive with Lazlo than he would ever reciprocate.<SPAN>&nbsp; </SPAN>But you never know what will happen.<SPAN>&nbsp; </SPAN>We’ll have to see.<SPAN>&nbsp; </SPAN></SPAN></P><br>
<P><SPAN>Source: Cartoon Network Pressroom (Now defunct)</SPAN></P>
<?php include "../footer.html"; ?>