<?php include("../header.php"); ?>
<P><FONT size=4>Everett Peck</FONT></P><P><B><SPAN>Q.<SPAN>&nbsp; </SPAN><I>Squirrel Boy is reminiscent of the classic cartoons on Saturday mornings. <SPAN>&nbsp;</SPAN>Was that your goal? <SPAN>&nbsp;</SPAN></I></SPAN></B></P>
<P><B><SPAN>A</SPAN></B><SPAN>. <I>Squirrel Boy</I> really is a tip of the hat to the classic Hanna-Barbara cartoons of the 1940s and 1950s, like <I>Tom and Jerry</I>. <SPAN>&nbsp;</SPAN>I was going for that classic feel when creating the look of the show. <SPAN>&nbsp;</SPAN>Also, I wanted to play the parents in the show as having emotional depth, and not as buffoons. </SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q. <I>Where did you grow up?</I></SPAN></B></P>
<P><B><SPAN>A</SPAN></B><SPAN>.<SPAN>&nbsp; </SPAN>I grew up in <st1:City w:st="on">Oceanside</st1:City>, <st1:State w:st="on">California</st1:State>, not too far from <st1:City w:st="on"><st1:place w:st="on">San Diego</st1:place></st1:City>.<SPAN>&nbsp; </SPAN>Then, I went to <st1:PlaceName w:st="on">Long Beach</st1:PlaceName> <st1:PlaceType w:st="on">State</st1:PlaceType> in <st1:State w:st="on"><st1:place w:st="on">California</st1:place></st1:State>, and now I live in Encinitas. <SPAN>&nbsp;</SPAN>I guess you could say I’m a <st1:State w:st="on"><st1:place w:st="on">California</st1:place></st1:State> boy. </SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q. <I>Who were some of your early influences?</I></SPAN></B></P>
<P><B><SPAN>A.</SPAN></B><SPAN> <SPAN>&nbsp;</SPAN>Before I knew anything it was Walt Disney – that’s all I knew. <SPAN>&nbsp;</SPAN>I equated his films with art. <SPAN>&nbsp;</SPAN>Then later on, it was Ward Kimball. <SPAN>&nbsp;</SPAN>When I was growing up there were no finely-tuned programs for kids like there are today. <SPAN>&nbsp;</SPAN>So you just watched what was on, like <I>Felix the Cat</I>. <SPAN>&nbsp;</SPAN>In high school I loved drawing with pen and ink and I got into Paul Clay, Mort Drucker, Saul Steinberg and Milton Glaser. <SPAN>&nbsp;</SPAN>And, of course, early underground comics by Robert Crumb.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q</SPAN></B><SPAN>. <B><I>Describe the process of creating a new character.</I></B></SPAN></P>
<P><B><SPAN>A</SPAN></B><SPAN>. It’s a simultaneous process. <SPAN>&nbsp;</SPAN>Generally, I get ideas from sketching people. <SPAN>&nbsp;</SPAN>I like to sit back, get a cup of coffee, watch people and sketch.<SPAN>&nbsp; </SPAN>With <I>Duckman,</I> I sketched him with a big muscle suit on. <SPAN>&nbsp;</SPAN>I like characters that are blowhards.<SPAN>&nbsp; </SPAN>I love that type of character and the relationships that character has. <SPAN>&nbsp;</SPAN>For me, it comes from drawing, and I’ll make notes in the margin and have the character saying something. <SPAN>&nbsp;</SPAN>Eventually, you build up a catalogue of characters to draw.</SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q.</SPAN></B><SPAN> <B><I>What is your approach for Squirrel Boy?</I> </B></SPAN></P>
<P><B><SPAN>A.</SPAN></B><SPAN> I suppose it’s what I like - funny, smart, good natured stuff. <SPAN>&nbsp;</SPAN><I>Squirrel Boy</I> appeals to kids, but parents will like it, too. I wanted to do a backyard-around-the-house-kind of show. <SPAN>&nbsp;</SPAN>It’s kind of like Saturday morning every day on the show. <SPAN>&nbsp;</SPAN>We don’t focus on Andy in school or Mr. Johnson going to work. With <I>Squirrel Boy</I>, I wanted to take a less cynical approach.<SPAN>&nbsp; </SPAN>There is so much stuff out there right now that relies on pop culture references. <SPAN>&nbsp;</SPAN>I just wanted to try something had a good-natured feel to it. <SPAN>&nbsp;</SPAN>A couple of buddies. <SPAN>&nbsp;</SPAN>Something with a friendly feel.</SPAN></P>
<P><B><SPAN></SPAN></B>&nbsp;</P>
<P><B><SPAN>Q. <I>What was your favorite part of putting together Squirrel Boy?</I></SPAN></B></P>
<P><B><SPAN>A.</SPAN></B><SPAN> The writing. <SPAN>&nbsp;</SPAN>The first time you see the visual with the audio – that’s exciting. <SPAN>&nbsp;</SPAN>The animatics and the recording sessions are great.<SPAN>&nbsp; </SPAN>Richard [Horvitz] is taking the character Rodney to new places. <SPAN>&nbsp;</SPAN>Once we get the film back for editing and start adding the music and the sound effects. <SPAN>&nbsp;</SPAN>It’s all a great process. </SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q.</SPAN></B><SPAN> <B><I>Discuss the classic look of the show.</I></B><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><B></B></SPAN></P>
<P><B><SPAN>A.</SPAN></B><SPAN> I wanted to make <I>Squirrel Boy</I> look brighter than real life and have the viewer feel like jumping into the cartoon. <SPAN>&nbsp;</SPAN>I wanted it to look like a bright Saturday morning. <SPAN>&nbsp;</SPAN>The elements; the trees, the Johnson’s house, their car, all have their own personality. <SPAN>&nbsp;</SPAN>Not literally of course, the car is not going to talk, but it’s going to stand out. <SPAN>&nbsp;</SPAN>It really adds to the overall feel. </SPAN></P>
<P><SPAN></SPAN>&nbsp;</P>
<P><B><SPAN>Q.</SPAN></B><SPAN> <B><I>What advice would you give to aspiring young illustrators just starting out?</I></B></SPAN></P>
<P><B><SPAN>A</SPAN></B><SPAN>. Having taught college for years, I told my students to develop a point of view, a way of looking </SPAN></P>
<P><SPAN>at the world. <SPAN>&nbsp;</SPAN>You’ll make it fit your point of view. <SPAN>&nbsp;</SPAN>If you have one, it will all fall into place.</SPAN></P><br>Source: Cartoon Network Pressroom (Now defunct)</span>
<?php include "../footer.html"; ?>