<?php include("../header.php"); ?>
<p><font face=Arial size=2><br><b><i>Quentin Tarantino Interview: Part 3</i></b></font></p>

<p><font face=Arial size=2><b><i>YL:  Tell us about some of your favorite music when you were young.</i></b></font></p>

<p><font face=Arial size=2><b>QT:</b>  My first favorite piece of music was probably the <i>Batman</i> theme. When I was a little kid, [the <i>Batman</i> theme] was probably, like, the music that would make me wet my pants.  Another song that I loved when I was a little kid was <i>Ballad of the Green Berets</i>.  I thought that that was a really great song, and I remember I was really into Elvis. One of his good hits.  One of his greatest hits.  But the <i>Partridge Family </i>was the rock album I bought.  It was the first music album I bought.  That was the first album that wasn't a kid's story book album, you know?  Ding!  You turn the page- 'after the ship wreck, the Swiss Family Robinson built their tree house.'  [<i>Partridge Family</i>] was my first record where no one talked on it, except for David Cassidy on a couple of songs.  So <i>The Partridge Family</i> was my first favorite group.  "I Think I Love You" was my first favorite hit, but as far as just hearing a song on the radio that became my love affair with pop music was probably <i>Sweet's</i> "Little Willy".   It was everyone's in the third grade class too—it was, like, that song was our favorite song.  I even remember one day we turned on the radio. It was, like, the one time we played the radio in class during school. When "Little Willy" played, all the kids in the class stopped. We listened to the song, we sung along with it, when it was over we kind of talked about it for, like, another 15 minutes.  And it was the first time that any of us, unless they had brothers or sisters who liked the song,  had a common pop culture thing.  We all knew we liked the song by ourselves. You talk about TV shows in school but you don't really talk about songs, especially in third grade.  And that was when I realized, Oh my God, everybody was just as connected to that song as I was.  Everyone was caught up in its hooks. Everyone was sad when it was over, just like me.</font></p>

<p><font face=Arial size=2><b><i>YL:  Did you go to arcades much? </i></b></font></p>

<p><font face=Arial size=2><b>QT:</b>  Well, the thing about it is, I had to get much older, because when I was in elementary school it was against the law for me to play pinball machines because pinball was considered gambling in Los Angeles county.  Because you won free games, for years, pinball was considered gambling; you had to be over 18 to play the pinball machine.  I barely remember this, but I'm remembering it now. I'd be in a bowling alley, and there they were. I didn't think about bowling, I thought about playing pinball, but I could not play it. It was considered gambling.</font></p>

<p><font face=Arial size=2><b><i>YL:  Tell us about your lunchbox collection.</i></b></font></p>

<p><font face=Arial size=2><b>QT:</b>  My lunch box collection is decent for someone who doesn't collect lunch boxes.  But it is not that impressive for a collector.  It is the most unimpressive of my collections.  Simply because I wanted to start collecting lunchboxes before I had the money to do it and I just couldn't make myself do it because they were just going out of control.  I just don't want to be raped, alright?  I don't mind paying something for it but I don't want to be raped.  They're just expensive and the guys screw ya, they just screw ya out of money and I just can't deal with that.  So, as opposed to 'I am going to go out and have the best collection in the world', I have always just been like a fun left handed collection.  I am not going to get raped but if along the way I can get one at a decent price…</font></p>

<p><font face=Arial size=2><b><i>YL:  What are some of your favorite lunchboxes?</i></b></font></p>

<p><font face=Arial size=2><b>QT:</b>  My Kung-Fu lunch box.  The best lunch box I have, hands down, is my <i>Man from U.N.C.L.E. </i>lunchbox.  I bought it for 45 dollars back when I made $8,000 a year. Which was all the money in the world to me.  It was mint condition.  Jack Davis did the art on it, which is just the bomb.  And it even had the thermos in it, in perfect condition.  I bought it for my friend Steve-o and gave it to him and it was the best gift I've ever given anybody, at least at that time.  And I love Steve-o but I should have kept that. That lunchbox would be $200. With the thermos intact? Perfect condition?  Forget about it.  But Steve-o gave me the lunch box back 8 years later.  Not because I had ever asked for it or anything like that.  He wanted to give me something.  And he said I've had it 8 years and now I think that you should have it. It was a great thing.  <i>Really</i> sweet.  So I proudly took it.  One of my other great ones that I have is this one Hanna Barbera one that on one side is Quick Draw McGraw and Baba Louie and the other side is Yogi Bear and Boo Boo. I'm not a big fan of Yogi Bear, but the thing that is so cool about it is the top of the lunch box where the handle is, is this little circle thing of all the different Hanna Barbara characters. What is great about it is it has the side characters.  It has Pixie and Dixie and Jinks the Cat, 'I hate meeses to pieces.' It even has that dog from Quick Draw McGraw 'Ah, ah, ah, ah, ah.'  You give him the biscuit.  I <i>love</i> that dog, he is one of my favorite characters.  "Ah, ah, ah, ah". So that one, and a friend of mine got me a Roy Rogers/Dale Evans lunchbox that I cherish.  Big Roy Rogers fan.  Big, big Roy Rogers fan.</font></p>

<p><font face=Arial size=2><b><i>YL:  Do you have an Evel Knievel lunchbox?</i></b></font></p>

<p><font face=Arial size=2><b>QT:</b><b> </b> I have a wonderful Evel Knievel lunchbox.  The Evel Knievel lunchbox is kind of cool because it kind of marks his shame.  The one side of it is the Snake River Canon which was at the end of his career 'cause it was such a joke.</font></p>

<p><font face=Arial size=2><b><i>YL:  Let's go back to Roy Rogers and Dale Evans.  Were you a fan of the movies and the TV show? </i></b></font></p>

<p><font face=Arial size=2><b>QT:</b><b> </b> Well, I was a very big fan of his drink, actually. He makes a hell of a cocktail, at least for boys.  I am far more into Roy Rogers now than I was as a little kid, but I knew Roy Rogers when I was a little kid.  I didn't watch the movies because they didn't show the movies on TV.  They showed the TV show, with him and Dale and his dog Bullet, and Pat Brady.</font></p>

<p><font face=Arial size=2>I got back into Roy Rogers majorly this last year.  There is this director named William Whitney who did the last five years of Roy Rogers film career and directed about 30 Roy Rogers movies in those five years.  I actually think William Whitney is one of my favorite directors now.  For my money, he is the best Western director in American film history.  I personally choose him over John Ford.  In watching Roy Rogers again, and what I so respond to, and I am sure that is what I exactly responded to as a little kid, is he just has such an incredibility sweet, decent, genuiness that just comes off him like you wouldn't believe.</font></p>

<p><font face=Arial size=2>I mean, it is so funny, because if you start watching those Gower Gulch B-westerns, which is actually kind of cool, so let me digress to two nanoseconds.  A friend of mine, Alex Rockwell, went to Louisiana and was standing in front of an old movie theater that was closed, and this 75 year old guy comes walking up to him. Alex is just looking at the closed movie theater and the 75 year old guy goes, 'Yeah, I remember living in this town my whole life, I remember when that theater was open.  I used to come down here, my mom would drop me off and I would watch the cowboys.  For a nickel.  All day long for a nickel.' It was funny 'cause I turned Alex on to Roy Rogers and director William Whitney and he brings up a few of those things and the old guy was like 'I don't remember the name of that guy.' Alex would talk to him about movies, westerns—he always referred to them as the cowboys.  Not westerns, not western movies, not anything—<i>the cowboys</i>.  'I used to come when I was a kid and watch the cowboys.  They made the cowboys.'</font></p>

<p><font face=Arial size=2><center><IMG SRC="p_roy_trigger.gif" width="123" height="164" ALT="p_roy_trigger.gif" align="left" border=0></center>Roy Rogers was one of the most natural actors since Elvis Presley.  He just never appeared to be acting.  Had this complete genuineness, almost like a soft-spoken Johnny Depp kind of genuineness that would just come off of him.  And there was also the fact that you knew him and Trigger had a bond.  I mean, Trigger was <i>his</i> horse. He was not the Republic horse of the studio.  A trainer didn't own him.  Roy Rogers owned Trigger.  Trigger was <i>his</i> horse.  They loved each other.  And by the way, I just think Trigger was the best animal actor in the history of cinema, even better than Asta, the little dog, in <i>The Thin Man</i> movies.</font></p>

<p><font face=Arial size=2>Asta was great.  As Pauline Kael said, Asta always looked like he adored every owner he had.  Whether it was Myrna Loy, William Powell, Irene Dunne, or Cary Grant. [Asta] just seemed devoted to them.  Trigger was even better.  William Whitney is the best director of animals in the history of cinema 'cause he loved animals.  Trigger would literally, in some of the movies, be the co-star; long scenes of Trigger by himself dealing with a pack of wild horses, Trigger falling in love with the leader of a pack of wild horses and their courtship.  It was just like, oh my God, I have never seen a movie where the animals just take over.  It was great.</font></p>

<p><font face=Arial size=2><b><i>YL: What are some of the fashions, like puka shells, for instance, that you remember from growing up?</i></b></font></p>

<p><font face=Arial size=2><b>QT:</b><b> </b> It's funny.  Just saying puka shells.  I don't know why that ever got a bad name, 'cause that still looks kind of cute today.  I look at <i>Dazed and Confused</i> and see Jason London's Pink Floyd character wearing the puka shells.  He looks pretty good in that.  If I would look that good, I would wear them.  You know, to tell you the truth.  I think I was fairly out of it when it came to fashion.  My idea of fashion was a Farrah Fawcett T-shirt.  Whoever I liked on the front of my T-shirt was my idea of fashion.  If I was wearing some jeans that didn't have a hole on the right knee then I was really putting on the dog.  As I got a little older, like 13, 14, I was just completely influenced by black fashion.  If I could have worn the lime green one-piece with the zipper, starts right here [indicating the chest] and ends at your crotch hairs, I would have been way into that.  I rejected everything surfer.  So I never wore that 70s white boy surfer stuff.  As I got a little older there was a black guy that lived in the house with us, renting a room from us. He was kind of this con-man kind of guy, kind of a father figure for a little bit and I would like, wear his s***.  Denim-suit, blue and white with the snaps and the thing, like window panes!  That window pane denim thing, alright? Eventually he gave it to me. That was like, man, you know what? White boy? 15 years old? I was the man!  I wore <i>it</i>, it didn't wear me.  I even remember, this is no joke, I was watching with Uma [Thurman] and Ethan [Hawke] the movie <i>Coffee</i> the other day and there is this scene where the pimp, King George, shows up and he's got the lime green suit. He's got the super-fly hat and the zipper kind of outfit.  And I turned to him and I go, 'you know what?  I'll tell you, the number one coolest thing about being older than you guys? I remember, I have a memory of when that was not to be laughed at.'</font></p>

<p><font face=Arial size=2>One little joke about fashion was the fact that I remember Dittos were a big thing with girls. And a funny thing, this guy named Mark goes 'they have Dittos for boys, don't they?'  'No, they don't have dittos for boys.'  And then one other kid goes, 'Oh no, they do, but only guys like Mark wear them.' 'Shut up!  <i>You</i> f*ing wear them, I don't wear them!'</font></p>

<p><font face=Arial size=2><b><i>YL:  What books do you remember?</i></b></font></p>

<p><font face=Arial size=2><b>QT:</b><b> </b> I could always read really, really well so I could like read <center><IMG SRC="p_luke_cage.gif" width="123" height="164" ALT="p_luke_cage.gif" align="left" border=0></center>adult books when I was very, very young.  I didn't all the time because they were kind of boring to me, but I <i>could</i>.  But I loved comic books.  I was really into comic books.  And, hands down, my favorite comic book in the mid-70s when it came out, was <i>Shang-Chi, Master of Kung-Fu</i>, which was sort of like the Kung-Fu comic book. It was really great.  But my favorite hero, the hero I wanted to be, was <i>Luke Cage, Hero for Hire</i>, which was basically the Blaxploitation comic book.  [<i>Luke Cage</i>] later became <i>Power Man</i>, but in the beginning he was, like, the black super hero.</font></p>

<p><font face=Arial size=2>I collected comic books and it was kind of cool, because back then if you lived in the suburb or if you lived in a project, it didn't matter, you probably had about six kids in the general area that collected comic books.  You could literally go to the kid's house and never having met him and bring your comic books with you, knock on his door, and you open the door, 'hi, my name is Quentin, are you Ken?  I heard you collect comic books.  I collect comic books too. Can I see your collection and I will show you mine?'  'Oh yeah, come on in.' It was a ritual.  You show out yours, you have your best ones, and you lay them out and everything and you kind of look at them.  And then he would lay out his and you'd look at them and go 'ooh and ahh' about your stuff and maybe you'd talk about trading. You could literally go into a kid's house you never knew before and start a friendship.  You're happy that someone cares. You are happy to show them.  So I did that, but the entire time I remember it was like 'Why do you like Luke Cage? He's black. Why do you like Luke Cage?'  Black kids 'Why do you like Luke Cage. He's black.'  I wasn't allowed to have Luke Cage be my favorite character.  That wasn't allowed.  That wasn't made for you.  It can't be your favorite character.  Only to grow up and find out that Nick Cage took his name from Luke Cage.   His name is Nicolas Coppola.  And when I found that out I went 'Oh my God, how cool!"</font></p>
<p>Source: Yesterdayland (Now defunct)</p>
</font>
<?php include "../footer.html"; ?>