<?php include("../header.php"); ?>
<p><font face=Arial size=2><center><IMG SRC="tarantino_mast.gif" width="150" height="220" ALT="tarantino_mast.gif" align="right" border=0></center>It can be said that few people have had the kind of
cultural impact that acclaimed writer/director Quentin
Tarantino has enjoyed.  He changed the face of cinema
forever with modern day classics <i>Reservoir Dogs</i> and
<i>Pulp Fiction</i>, one the most influential movies of the
last decade, if not of all time.  Studied by the
academia and quoted by the masses, his films are
jammed with enough clever pop culture references to
fuel a thousand slumber parties and water cooler
conversations.<br>
<br>
Now, Yesterdayland takes you behind the cameras to
talk to the man who made Travolta cool again.
From his early obsession with Evel Knievel to his
bombastic GI Joe backyard battles to his painful
recollections of "Cap'n Crunch Mouth", here is the one
and only Quentin Tarantino.</font><br clear="all"/>       			          
																		<p><font face=Arial size=2><b><i>YESTERDAYLAND: What was some of your favorite Saturday morning cartoons?</i></b></font></p>

<p><font face=Arial size=2><B></B><b>QUENTIN TARANTINO:</b> I remember my least favorite Saturday morning cartoon was definitely <i>Scooby Doo</i>. <center><IMG SRC="p_scooby.gif" width="123" height="164" ALT="p_scooby.gif" align="left" border=0></center>I hated <i>Scooby Doo</i>. I thought it was a stupid show, I mean, I actually remember watching the first episode ever shown of <i>Scooby Doo</i>, like the season it started. I go 'what the heck is this thing?' I never thought the mysteries were good. I always thought it was stupid and, then, I don't know if this is the case with all of the shows, but it seems like <i>Scooby Doo</i> started the thing where they made six episodes every year. They proceeded to repeat the same six episodes every year and then when <i>Scooby Doo</i> hit then all of a sudden on Saturday morning it was like you had six shows and then for the rest of the year it was just repeating them again and again and again. My dislike of <i>Scooby Doo</i> was a big thing. As far as like my favorite shows when I was really little, I loved <i>H.R. Pufnstuf</i> and I think Pink Panther was really funny but, I really liked <i>H.R. Pufnstuf</i></font></p>

<p><font face=Arial size=2><b><i>YL: I know that breakfast cereal is a passion of yours, I want you to talk about some your favorite breakfast cereals and then I want you to talk about why you love <i>Bill and Ted's Excellent Cereal</i>.</i></b></font></p>

<p><font face=Arial size=2><b>QT:</b> One of the reasons that I like breakfast cereal is: one, it's <i>really</i> good, and two, it's <i>really</i> <center><IMG SRC="p_bill_tedz.gif" width="123" height="164" ALT="p_bill_tedz.gif" align="left" border=0></center>easy to fix. If you've got a good box of cereal, what could you possibly make in your house that's gonna be better than that bowl? Everything else will take so much more time then making that bowl of cereal. Cereal's like pizza: you just eat it until you get sick. I've always loved the fact that cereal is still really aimed at kids and is more fashionable and faddish than a hip-hop tennis shoe, because they will literally, constantly, come out with, like, "butterscotch toast cereal", alright? And it's on the stands for three months and then it's <i>gone</i>. Never to be heard of again. Especially all of the cereals they tie in with this movie or that Saturday morning cartoon or this show or this that and the other. That's always cool I like collecting stuff. I'm a collector of stuff, and so it's, like, 'Oh, I remember Hong Kong Phooey Crunch' or whatever. I have to say, most the time, they take a cereal and they do some Urkelo's or whatever, it's just another cereal like one you had before, just with a different color and a different form of a marshmallow in it or something like that. <i>Bill and Ted's Excellent Cereal</i> was an exception to the rule. It was cool. It wasn't based on the movie, it was based on the cartoon. If they had a <i>Dumb and Dumber</i> cereal, they would have the cartoon <i>Dumb and Dumber</i>, not the Jeff Daniels on the cover. It was good; it tasted better than Lucky Charms. It was really good. It had the cartoon drawing of Bill and Ted on there and I was like, 'man, I should call up General Mills and get a year's supply of this, cause it's gonna be on the stands for four months and then it's gonna go away and never to be seen again.'</font></p>

<p><font face=Arial size=2><b><i>YL: What are some of your favorite classic cereals?</i></b></font></p>

<p><font face=Arial size=2><b>QT:</b> Well, <i>Cap'n Crunch</i> cereal, that's kinda the classic, that's the Crystall of cereal. All of its different versions. I liked <i>Crunch Berries</i>, I even liked <i>Peanut Butter Crunch</i>, though peanut butter gets a little too much. But I still kinda like it, until that third bowl. I think [<i>Cap'n Crunch</i>] has the distinction that a modern ailment has been named of it. I use it and everyone knows what I'm talking about it when I use it. It's "Cap'n Crunch Mouth", which means you've had one bowl too many of <i>Cap'n Crunch</i> and now the roof of your mouth is hanging like shards, little strips of your gums are dangling like stalagmites. That's "Cap'n Crunch Mouth". I kinda like the fact that <i>Cap'n Crunch</i> is, like, the greatest thing in the world until all of a sudden you feel like you're eating ground glass. But, until you have the feeling of eating ground glass, it's the greatest thing in the world. What is that? Like, a swami or something? It hypnotizes you and then you come out of it. When the pain is too excruciating and then finally 'oh my God, I am eating ground glass.'</font></p>

<p><font face=Arial size=2><b><i>YL: Anything with prizes in it that you've collected in cereal?</i></b></font></p>

<p><font face=Arial size=2><center><IMG SRC="p_captn_crunch.gif" width="123" height="164" ALT="p_captn_crunch.gif" align="left" border=0></center><b>QT:</b> There was this kinda thing when you're a kid- if you're gonna buy a cereal that didn't have a prize in it, when there were obviously cereals that had prizes in the box, you felt like were missing an opportunity or something. You would never buy it. Even if you liked it, you'd never buy <i>Kix</i>. They don't have prizes in it. There's your grandma's cereal, and then there was cereal for you. Cereal and Saturday morning; they all worked together. Saturday morning was your time. That was your Vegas. That was when the network was for you, when parents didn't even bother to wake up. That was cool. Cereal was yours and you could make that and enjoy it. Prizes were always a pretty big deal when I was little. But, the better the prize, the worse the cereal. I mean, if you got a swiss army knife in a box of cereal, you knew that you weren't gonna like the box of cereal, if you got some crappy tattoo that's gonna look like a birth mark when you put it on your arm, that's probably the good cereal.</font></p>

<p><font face=Arial size=2><b><i>YL: Did you listen to any old radio shows?</i></b></font></p>

<p><font face=Arial size=2><b>QT:</b> That's about twenty years before my time, however, I remember when I was a little kid- about ten- actually feeling nostalgic about a past that I never had when it came to radio shows. In the seventies they had, it wasn't KTEL but it was a [KTEL-like] version of an old radio show album. They had commercials on TV, "Go back to the fun days of yester year." It was like a four album set that had twenty minute episodes of these different shows and they were doing the whole thing, "Who knows? The Shadow knows…," or "Welcome to <i>Gang Busters</i>." (makes gun shot). I went, 'Wow, that sounds great!' and remember my step-dad telling me, 'Oh man, <i>Gang Busters</i> was a great show, it was great gangster show, it was excellent. Oh, the Shadow was great. That's Orson Welles, you know that, Quentin?' And so I was like 'I wanna hear those shows', the way, I guess, kids now who went 'wow that stuff from the seventies sounds pretty cool. I'd like to be able to watch the <i>The Partridge Family</i> every Friday or <i>Get Christy Love</i> or whatever. That's how I felt when I was watching the commercial for <i>Gang Busters</i>.</font></p>

<p><font face=Arial size=2><b><i>YL: What's your earliest TV memory and what were your favorite shows?</i></b></font></p>

<p><font face=Arial size=2><center><IMG SRC="p_batman2.gif" width="123" height="164" ALT="p_batman2.gif" align="left" border=0></center><b>QT:</b> If you asked my mom she would definitely tell you that my first favorite TV show, that I was obsessive about, was <i>Batman</i>. I don't even like <i>Batman</i> now, but I remember when I was a little kid, I was pretty gonzo about it. I lived in El Segundo for most of my memories of childhood, but I did live a little bit in another area. When I was, like, three and four and one of the few memories I <i>do</i> have is that I remember watching <i>Batman</i>. I <i>do</i> remember being excited turning on <i>Batman</i>. I even remember some car in the parking lot of the apartment building we lived in. It was like a Volkswagen kinda car and in that little back window that the Volkswagen has, that little triangle window, there was a decal of the Batman logo of the spotlight, you know, the sixties one. I remember always passing that car and looking at that thing longingly. Even kinda staring at it for a little bit. I just thought it was so cool that someone even had a Batman logo on their car and why didn't we have one on our car?<br></font></p>
<p>Source: Yesterdayland (Now defunct)</p>
</font>
<?php include "../footer.html"; ?>