<?php include("../header.php"); ?>
<P><FONT size=4>Genndy Tartakovsky Talks About Star Wars: Clone Wars</FONT></P><P>Q.<SPAN>&nbsp; </SPAN><B>How was <I>Star Wars: Clone Wars</I> project initiated?<SPAN>&nbsp; </SPAN>Did Lucasfilm first contact Cartoon Network or vice-versa?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>The project came together through joint conversations between Lucasfilm and Cartoon Network.<SPAN>&nbsp; </SPAN>Lucas wants to keep the <I>Star Wars</I> property robust and active between motion picture releases.<SPAN>&nbsp; </SPAN>So they approached me and asked if I would be interested in creating a one-minute program based on <I>Star Wars</I>.<SPAN>&nbsp; </SPAN>Well, of course I said “yes,” but told them that I couldn’t really do anything significant with one-minute episodes—it’s simply too short a time to tell a story.<SPAN>&nbsp; </SPAN>Cartoon Network went back to Lucasfilm and told them that they would be working with the team behind <I>Samurai Jack </I>(Emmy-winning series created by Tartakovsky).<SPAN>&nbsp; </SPAN>And it turns out that George Lucas watches and really admires <I>Samurai Jack</I>, so they sent word that we now would be worthy of creating three-minute <I>Star Wars</I> episodes!</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>After working for years in half-hour formats, how did you go about preparing three-minute episodes?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>When we got the greenlight from Lucasfilm, I still wasn’t really sure even three-minutes would work.<SPAN>&nbsp; </SPAN>So I took several existing 22-minute episodes of <I>Samurai Jack</I> and re-edited them into three-minute versions to see what I had.<SPAN>&nbsp; </SPAN>I wanted to know that in three minutes you could make sense, capture the viewer’s interest and still tell a compelling story.<SPAN>&nbsp; </SPAN>And I found that it actually worked, particularly if each installment worked to build upon the previous one, to offer an important piece to the overall story arc, then end with a cliff-hanger that would inspire the viewer to come back to see what happens next.<SPAN>&nbsp; </SPAN>I think you’ll see that each episode, despite being only three minutes long, has a beginning, middle and an end that pulls the viewer in and makes him or her want to know more.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>What is Lucasfilm’s involvement with the creation of the series?<SPAN>&nbsp; </SPAN>Has the company told you what storyline to follow or have they given you a free hand?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>They’ve been remarkably hands-off with us about <I>Clone Wars</I>.<SPAN>&nbsp; </SPAN>I think once George Lucas gave his overall blessing or “seal of approval” because of what we’ve achieved to date with <I>Samurai Jack, </I>everyone felt they could trust us to handle the property with the appropriate care and concern it deserves.<SPAN>&nbsp; </SPAN>So we went away and developed our own storyline, a new perspective and approach, along with character designs and production elements—all of which really excited us—and we brought it back and pitched the new scenario to them.<SPAN>&nbsp; </SPAN>And fortunately, everyone really loved it.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>So what is this new scenario, your particular angle, to the <I>Star Wars</I> story?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>Because this project is composed of so many different short segments, I like compare it to HBO’s <I>Band of Brothers</I>, a project I really admired that takes a huge story like the European Allied campaign of World War II and presents it in a series of “a day in the life of” stories.<SPAN>&nbsp; </SPAN>As I see it, this project mirrors that approach by showcasing several “days in the life of the Clone Wars.”<SPAN>&nbsp; </SPAN>For instance, in the first few episodes, we’re presenting a singular, but extremely important campaign, <I>The Battle of Muunilinst</I>, an all-city planet under attack by the Separatist movement.<SPAN>&nbsp; </SPAN>We’re able to explain the goals and obstacles the old Republic and Jedi must face, reveal important internal conflicts between the main characters, and still have time to highlight the action of the battle.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Was there anything off-limits or forbidden to you from the original story?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>Really, there was only one area where we were told by Lucasfilm not to approach, and that had to do with the love-story between Anakin and Padmé.<SPAN>&nbsp; </SPAN>We actually had an idea originally where at some point in the middle of the war, Anakin would have a quiet moment and he would take out a small hologram picture of Padmé and reflect upon how much he misses her.<SPAN>&nbsp; </SPAN>But since we were told not to explore any romantic interest in the story, we had to let that go.<SPAN>&nbsp; </SPAN>You will see Padmé, though, in the very first episode as she waves goodbye and later on in the series.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Did you have to produce storyboards for Lucasfilm before moving ahead with actual production, or did you plunge ahead once they approved the original overall storyline?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>Once we presented the overall outline covering the 20-episode series, we wrote one or two-sentence descriptions for each individual installment.<SPAN>&nbsp; </SPAN>After these were approved, we then created storyboards for these episodes and shared them with the partners.<SPAN>&nbsp; </SPAN>But since we were working within a tight timeframe to meet the Fall ’03 premiere, we immediately began production on each chapter once the storyboards were finalized.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Were you a <I>Star Wars</I> fan as a kid?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>Oh yes, of course.<SPAN>&nbsp; </SPAN>Really, everyone my age grew up with <I>Star Wars</I>.<SPAN>&nbsp; </SPAN>It was definitely one of the first big movies I saw after immigrating to America.<SPAN>&nbsp; </SPAN>I think it truly is one of the most inspirational, most influential movies of our generation.<SPAN>&nbsp; </SPAN>It certainly inspired me to dream of worlds beyond the here and now.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Do you have any specific memories of watching <I>Star Wars</I> for the first time?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>Not really…but what I do remember is how much I wanted to buy the toys, the action figures and the space vehicles!<SPAN>&nbsp; </SPAN>We didn’t have a lot of money while growing up, so there wasn’t much I could afford to buy.<SPAN>&nbsp; </SPAN>So I only had a few of the actual main figures.<SPAN>&nbsp; </SPAN>But I remember trying to save up every bit of money I could so that I could buy just one more character to play with.<SPAN>&nbsp; </SPAN>All I know is that I kept thinking, “I need more toys!”</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>So do you have all the <I>Star Wars</I> toys now?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>No, no.<SPAN>&nbsp; </SPAN>I got over that phase and moved on toward thinking more about the stories themselves, how they were constructed, the imaginary worlds that comprised <I>Star Wars</I>, the characters, that sort of thing.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Is working on the project a “dream come true?”</B></P>
<P>A.<SPAN>&nbsp; </SPAN>It’s certainly fulfills one of my dreams, to work on a project like <I>Star Wars</I> that is so thoroughly established it has become a part of our culture.<SPAN>&nbsp; </SPAN>Here’s one of the biggest phenomena of our generation and I get to add my own voice to it!<SPAN>&nbsp; </SPAN>I get to be a part of it, to share in its ongoing creation.<SPAN>&nbsp; </SPAN>That’s an awesome assignment and I’m really honored to be a contributor to its legacy.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Were you at all scared to take on such a cultural icon?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>Oh, yeah, absolutely.<SPAN>&nbsp; </SPAN>At first I thought it really might be more fun for someone else to do it, and then I could just sit back and watch the show!<SPAN>&nbsp; </SPAN>Because an animated <I>Star Wars</I> is such a cool idea.<SPAN>&nbsp; </SPAN>But then I thought, “what if they make it wrong?”<SPAN>&nbsp; </SPAN>Then I would be really upset, and I’d be left with nothing to do but complain, “well, WE should have made it!”<SPAN>&nbsp; </SPAN>So, because I’m a rather aggressive person, I reasoned that I’d better take the challenge myself.<SPAN>&nbsp; </SPAN></P>
<P>What I should add, though, is that once we accepted the project, literally everyone who was to work on it found themselves extremely hesitant to take the first steps.<SPAN>&nbsp; </SPAN>Paul Rudish, the art director for the show, with whom I’ve worked for years on <I>Dexter’s Laboratory</I> and <I>Samurai Jack</I>, is the type of guy who can draw anything, anytime and anywhere without hesitation—he’s amazing.<SPAN>&nbsp; </SPAN>But on the first week of <I>Star Wars: Clone Wars</I>?<SPAN>&nbsp; </SPAN>Complete brain freeze at the drawing board!<SPAN>&nbsp; </SPAN>Absolutely nothing would come forth.<SPAN>&nbsp; </SPAN>He couldn’t draw, couldn’t come up with a palate, anything.<SPAN>&nbsp; </SPAN>And he knows <I>Star Wars</I> better than anyone on the team—could normally draw R2-D2 free-hand in total perspective with all the mechanical gadgets…now nothing!<SPAN>&nbsp; </SPAN>We finally had to take our minds off the enormity of it all and just approach this thing like any other project. <SPAN>&nbsp;</SPAN>At last, once we relaxed, it all began to flow naturally.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Do you have a favorite character from <I>Star Wars</I>?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>I think Han Solo and Chewbacca are my favorites.<SPAN>&nbsp; </SPAN>As pirates, they were the true rebels among the cast of characters.<SPAN>&nbsp; </SPAN>And Han Solo had such a cool charisma about him.<SPAN>&nbsp; </SPAN>He was the bad-boy character, but he still helped out when everyone needed him.<SPAN>&nbsp; </SPAN>I was such a “good kid” when I was young, I think I wanted to secretly break out and be more like Han.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Any least favorite character(s) you didn’t want to deal with?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>I think I’ll just say “no comment” to that one…</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Do you have plans to work on more projects with Lucas or Lucasfilm?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>Nothing definite, but hopefully, yes.<SPAN>&nbsp; </SPAN>The relationship between us so far has been very good.<SPAN>&nbsp; </SPAN>His name and the company name have become such leading brands in entertainment industry.<SPAN>&nbsp; </SPAN>So to have their support for this project really helps bring animation into the spotlight, which isn’t always an easy thing to do.<SPAN>&nbsp; </SPAN></P>
<P>Q.<SPAN>&nbsp; </SPAN><B>What animation processes are you using with this project?<SPAN>&nbsp; </SPAN>Is there CGI (computer generated imaging) involved, or 3D?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>Most of the visual elements in <I>Star Wars: Clone Wars</I> have been created through traditional cel animation at this point.<SPAN>&nbsp; </SPAN>However, we have added CGI elements to the production, including computer-generated spaceships that help create the action and excitement of the dog-fights in space that are so much a part of the <I>Star Wars </I>appeal.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Can you tell me more about the sound and soundtrack to the production?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>One of the signature elements to <I>Star Wars</I> is the unique sound Lucasfilm created for the motion picture series.<SPAN>&nbsp; </SPAN>We were extremely fortunate to have Skywalker Sound create the sound effects and background elements for <I>Star Wars: Clone Wars</I> as well.<SPAN>&nbsp; </SPAN>I was amazed that when the tapes came back to us from Skywalker the whole show suddenly seemed “legitimate.”<SPAN>&nbsp; </SPAN>I mean it had the same recognizable sounds as any one of the feature films.<SPAN>&nbsp; </SPAN>We simply couldn’t have reproduced this sound on our own.<SPAN>&nbsp; </SPAN>Every single sound effect in <I>Clone Wars</I> comes directly from the library comprised of the first five movies.<SPAN>&nbsp; </SPAN>And the best part is that we have several new individual sounds in our production that came from mixing two or more different sounds used in the films.</P>
<P>And as for the music, we’ve been able to use the classic, Oscar-winning John Williams compositions that Star Wars fans expect to hear.<SPAN>&nbsp; </SPAN>Again, this familiar music just makes <I>Star Wars: Clone Wars</I> completely “legitimate.”</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Because Lucasfilm had admired the original work, is the team now working on <I>Star Wars: Clone Wars</I> the same team that produced <I>Samurai Jack</I>?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>Yes, the same production team is in place on both projects, but the look of the two shows is definitely individual, distinct from the other.<SPAN>&nbsp; </SPAN><I>Samurai Jack</I> is a far more stylized, design-driven show, while <I>Star Wars: Clone Wars</I> is much more realistic.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Speaking of realism, how did you go about creating the realistic animated versions of the characters within <I>Clone Wars</I>?<SPAN>&nbsp; </SPAN>Did you try to copy to face and bodies of the live-action characters in the films?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>This actually presented our first stumbling block.<SPAN>&nbsp; </SPAN>Originally, Paul Rudish kept drawing the actors (or caricatures of them) who portrayed the roles in the motion pictures.<SPAN>&nbsp; </SPAN>But this didn’t come out right—they didn’t look like the essence of the character they were supposed to be.<SPAN>&nbsp; </SPAN>So we started experimenting and determined that our own versions of the characters, ones that merely resembled the actors who played them onscreen, and it worked better in the long-run.<SPAN>&nbsp; </SPAN>They still have qualities that reflect the actors who originally portrayed them, but there are also elements which are drawn from our thoughts about the character.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>The voices of the animated characters sound very much like the actors who portrayed them in the movies.<SPAN>&nbsp; </SPAN>Are they the same?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>That actually was a big concern of mine, that the voices sound authentic.<SPAN>&nbsp; </SPAN>No, the actors in the animated series are amazingly talented voice-artists who were able to create readings that are incredibly close to their live-action counterparts.<SPAN>&nbsp; </SPAN>And they were such good actors, too, which made the recordings a wonderful experience overall.<SPAN>&nbsp; </SPAN>Only Anthony Daniels, the original C-3PO, supplies the voice for both the live-action and animated versions of his character.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Would you say this was the most challenging aspect to the project?<SPAN>&nbsp; </SPAN>Or was it something else?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>I think casting voice talent was one of the big challenges upfront, but then we rather quickly settled that issue and moved forward.<SPAN>&nbsp; </SPAN>To me, the biggest challenge was to create that unique <I>Star Wars</I> “feel” for the series.<SPAN>&nbsp; </SPAN>There is something quite singular about <I>Star Wars</I> that makes it very extraordinary.<SPAN>&nbsp; </SPAN>There are a ton of science-fiction films and TV series that have been produced over the years, but none of them feel like a true <I>Star Wars</I> property.<SPAN>&nbsp; </SPAN>So what is it that makes something feel like <I>Star Wars</I>?<SPAN>&nbsp; </SPAN>As I analyzed the question, I realized that there were many answers one could name: the triangular space ships slowly moving into the picture above frame, the sound of the vehicle engines, the particular art direction used for both internal and external sets, the unique space creatures that appear throughout each film, the sense of duty and honor to the Jedi traditions, etc.<SPAN>&nbsp; </SPAN>After all of this research, I finally reached a place where I could watch what we produced and confidently say, “THIS is <I>Star Wars</I>.”</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>How many times did you watch the <I>Star Wars</I> films in order to get ready for this project?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>I didn’t go back to watch them at all.<SPAN>&nbsp; </SPAN>Actually, I did go back to the second move, <I>The Empire Strikes Back</I>, to study a little bit of how the robots moved, but otherwise not at all.<SPAN>&nbsp; </SPAN>We all wanted to, but the project came up so fast and we were moving so quickly on it, we just didn’t have time to sit down for eight hours to review the films.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Did you then simply rely on your memory of the films and the characters?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>Yes.<SPAN>&nbsp; </SPAN><I>Star Wars</I> is frankly so embedded in us, we really didn’t have to go back to the films.<SPAN>&nbsp; </SPAN>We all had seen the films so many times before and we each had particular moments within each film that have stayed with us.<SPAN>&nbsp; </SPAN>There really wasn’t a need to go back again to review what we already knew by heart.<SPAN>&nbsp; </SPAN>I speak primarily about myself, too, because since I would be responsible for putting it all together, I already knew what key elements we had to have.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Was there a particular moment as a child that you remember most from <I>Star Wars</I>?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>I particularly remember the light-saber fights, the distinct sound of them gliding through the air and the movements the actors used as they fought with them.<SPAN>&nbsp; </SPAN>And I remember the X-Wing Fighters coming into formation and opening up for battle.<SPAN>&nbsp; </SPAN>Those moments will be with me forever.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>If you were commissioned right now for your next dream project, what would that project be?</B></P>
<P>A.<SPAN>&nbsp; </SPAN>It would definitely be to create and direct a 2D theatrical feature film.<SPAN>&nbsp; </SPAN>I think I’m ready for that now.</P>
<P>Q.<SPAN>&nbsp; </SPAN><B>Do you know what happens next for the <I>Star Wars</I> characters in Episode Three of <I>Star Wars</I>?</B></P><SPAN>A.<SPAN>&nbsp;&nbsp;</SPAN>Well, we all know where they end up generally by Episode IV (the original <I>Star Wars</I> film), but I haven’t been briefed about what will actually occur in </SPAN><br>Source: Cartoon Network Newsroom (Now defunct)</span>
<?php include "../footer.html"; ?>