<?php include("../header.php"); ?>
<P><FONT size=4>Genndy Tartakovsky Talks About His Work on Samurai Jack</FONT></P><P><B><SPAN>What was your inspiration for <I>Samurai Jack</I>?</SPAN></B></P>
<P><SPAN>After doing <I>Dexter's Laboratory</I> and <I>The Powerpuff Girls</I>, I really wanted to create something different. </SPAN></P>
<P><SPAN>My goal in creating <I>Samurai Jack</I> is to develop a highly stylized action show.<SPAN>&nbsp; </SPAN>I love action and I love action shows, but I've never seen a show that has enough action to satisfy me.<SPAN>&nbsp; </SPAN>And I also wanted to do something sincere like <I>Dexter's Laboratory</I>.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><SPAN>I decided I wanted to create good action that's choreographed and I liked samurai.<SPAN>&nbsp; </SPAN>So I came up with a back story and it all started to come together.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><B><SPAN>Tell us about Jack and his nemesis, Aku.</SPAN></B><SPAN></SPAN></P>
<P><SPAN>Jack is the son of an emperor who has been defeated by an evil wizard.<SPAN>&nbsp; </SPAN>Jack has undergone physical and scholarly training around the world, then returns to liberate his people. Before he has a chance to destroy him, the wizard, Aku, tricks him and sends him into the future. The future is miserable: everybody is unhappy, everybody is under the grasp of Aku.</SPAN></P>
<P><SPAN>Jack is heroic.<SPAN>&nbsp; </SPAN>He's a great warrior, but he's also very sympathetic.<SPAN>&nbsp; </SPAN>He's not invulnerable.<SPAN>&nbsp; </SPAN>He loses, but weaknesses make his character stronger.<SPAN>&nbsp; </SPAN>There is just something very mythological about him.<SPAN>&nbsp; </SPAN>Jack must return to the past to undo the wrongs that have been done.<SPAN>&nbsp; </SPAN>It's a basic good versus evil story.</SPAN></P>
<P><SPAN>Aku is just pure evil.<SPAN>&nbsp; </SPAN>Although he is evil and creepy, he is very appealing.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><B><SPAN>Is this an anime show?</SPAN></B></P>
<P><SPAN>Anime is one of the small influences on <I>Samurai Jack</I>.<SPAN>&nbsp; </SPAN>Anime characters use only limited expressions.<SPAN>&nbsp; </SPAN>Most action characters are stoic and straight without much life, but we made Jack more of an emotional character by giving him big, expressive eyes so that his character has more of a range like Dexter and other animated comedy characters.<SPAN>&nbsp; </SPAN></SPAN></P>
<P><B><SPAN>&nbsp;</SPAN></B><B><SPAN>How does <I>Samurai Jack</I> differ from other cartoons stylistically?</SPAN></B></P>
<P><SPAN>I wanted to do something different than anything else I had ever worked on.<SPAN>&nbsp; </SPAN>We have a great background painter who has built an amazing mood through the backgrounds.<SPAN>&nbsp; </SPAN>Environment and the background really are major characters in <I>Samurai Jack</I>. </SPAN></P>
<P><SPAN>Music is also a huge key. Because Jack travels to different civilizations we incorporated a lot of culture and ethnicity into the music.<SPAN>&nbsp;&nbsp; </SPAN>It will be filtered and twisted and mutated, combining classical and traditional elements with traces of hip-hop and techno to come up with something new.</SPAN></P>
<P><B><SPAN>Will <I>Samurai Jack</I> appeal to both kids and adults?</SPAN></B></P>
<P><I><SPAN>Samurai Jack</SPAN></I><SPAN> is for everybody.<SPAN>&nbsp; </SPAN>It has comedy, action and adventure; it's all those things combined.<SPAN>&nbsp; </SPAN>From show to show you will never guess what will happen next.<SPAN>&nbsp; </SPAN>I think that it is going to be the most unique and different experience viewers have had watching a cartoon.<SPAN>&nbsp; </SPAN>Hopefully, people will really feel like this is a new mythology and they will want to follow the legend.<SPAN>&nbsp; </SPAN>For kids, it has great samurai action.<SPAN>&nbsp; </SPAN>Adults will appreciate the great filmmaking, the mood and the humor.</SPAN></P>
<P><B><SPAN>What are some of your influences for the action elements of <I>Samurai Jack</I>?</SPAN></B></P>
<P><SPAN>I grew up loving everything from Bruce Lee to Kurosawa films. <SPAN>&nbsp;</SPAN>I love Clint Eastwood in old spaghetti westerns.<SPAN>&nbsp; </SPAN>It's all kind of the same thing.<SPAN>&nbsp; </SPAN>When you're a kid, you like that kind of stuff.<SPAN>&nbsp; </SPAN>And I still like it.</SPAN></P>
<P><B><SPAN>How does <I>Samurai Jack</I> differ from Dexter?</SPAN></B></P>
<P><SPAN>Jack is an adult with a mission in life, while Dexter is a grumpy kid. <I>Samurai Jack</I> is darker in tone because he's trying to avenge his people and undo all the wrong that has been done through the centuries. Dexter is just trying to work in his lab without being bothered by his sister, while Jack has a far more serious motivation</SPAN></P><br>Source: Cartoon Netork Pressroom (Now defunct)</span>
<?php include "../footer.html"; ?>