<?php include("../header.php"); ?>
<P><FONT size=4>Judd Winick</FONT></P><P ><SPAN >Q:<B><SPAN >&nbsp; </SPAN>Where did the idea for <I>The Life &amp; Times of Juniper Lee</I> come from?</B></SPAN></P>
<P ><SPAN >A:<SPAN >&nbsp; </SPAN>The truth is that my wife Pam and I went out and decided to come up with what would be the funniest show for us to do.<SPAN >&nbsp; </SPAN>Forgetting where it would appear or who would watch it, we thought, “What would we really love to make?”<SPAN >&nbsp; </SPAN>I love everything from <I>Buffy the Vampire Slayer</I> to <I>Hellboy</I>.<SPAN >&nbsp; </SPAN>I love magic and monsters and superhero stories.<SPAN >&nbsp; </SPAN>So we started putting that all together to create <I>The Life &amp; Times of Juniper Lee</I>.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<P ><SPAN >My wife wanted to have an Asian protagonist because there are so few of them on television.<SPAN >&nbsp; </SPAN>Pam wanted the character to be like her and her sisters, just a normal American girl.<SPAN >&nbsp; </SPAN>Her culture is Chinese, but that is not only who she is.<SPAN >&nbsp; </SPAN>She grew up as a typical American kid, and that is the direction we went with Juniper Lee.<SPAN >&nbsp; </SPAN>Her culture is just one part of who she is.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<SPAN >Q:</SPAN><SPAN ><SPAN >&nbsp; </SPAN>What are other similarities between your wife and Juniper?</SPAN>
<P ><SPAN >A:<SPAN >&nbsp; </SPAN>Juniper looks a lot like Pam.<SPAN >&nbsp; </SPAN>Pam has colored streaks in her hair, and that’s where Juniper gets hers.<SPAN >&nbsp; </SPAN>Pam says Juniper looks like Pam on the outside, but is all Judd on the inside.<SPAN >&nbsp; </SPAN>Juniper is more snarky and rude to her elders than Pam could ever be. <SPAN >&nbsp;</SPAN>Pam is tough, funny and sarcastic and all of that is also in Juniper Lee.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<P ><SPAN >Q:</SPAN><SPAN ><STRONG><SPAN >&nbsp; </SPAN>What is Juniper Lee’s role in the show?<SPAN >&nbsp; </SPAN>What is her central conflict?</STRONG></SPAN></P>
<P ><SPAN >A:<SPAN >&nbsp; </SPAN>In June’s world, in Orchid Bay, there is a world of humanity and a world of magic.<SPAN >&nbsp; </SPAN>Magic is all around but you can’t see it.<SPAN >&nbsp; </SPAN>Monsters and creatures and magic are invisible to everybody, with the exception of a chosen few, called the <I>Te Xuan Ze</I>.<SPAN >&nbsp; </SPAN>Juniper Lee is one of the chosen few and her job is to maintain the harmony between the world of humanity and the world of magic.<SPAN >&nbsp; </SPAN>She makes sure that monsters don’t mess with humans and humans don’t mess with monsters.<SPAN >&nbsp; </SPAN>She wears a little bracelet that is like a beeper, alerting her when something is wrong.<SPAN >&nbsp; </SPAN>But part of Juniper’s character is that she is a reluctant hero.<SPAN >&nbsp; </SPAN>She actually would rather be a regular kid who just goes to school and hangs out with friends.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<SPAN >Q:</SPAN><SPAN ><SPAN >&nbsp; </SPAN>Who else from Juniper Lee’s family can see the world of magic?</SPAN>
<P ><SPAN >A:<SPAN >&nbsp; </SPAN>This has been the job of one member in her family for generations.<SPAN >&nbsp; </SPAN>The <I >Te Xuan Ze</I> before June was her grandmother, Ah-Mah.<SPAN >&nbsp; </SPAN>But now it’s Juniper’s responsibility.<SPAN >&nbsp; </SPAN>Her little brother Ray Ray can also see monsters and magic, so he comes along with June.<SPAN >&nbsp; </SPAN>He loves the action and adventure.<SPAN >&nbsp;&nbsp; </SPAN>And Monroe is the obligatory talking dog who, as it turns out, is hundreds of years old and has been doing this for centuries.<SPAN >&nbsp; </SPAN>He has been the official sidekick of all the <I>Te Xuan Ze</I> for generations.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<P ><SPAN >Q:</SPAN><SPAN ><STRONG><SPAN >&nbsp; </SPAN>Why is your protagonist female?<SPAN >&nbsp; </SPAN>Is there a girl power theme or is she just a great character?</STRONG></SPAN></P>
<P ><SPAN >A:<SPAN >&nbsp; </SPAN>The idea of it being a boy character never occurred to me.<SPAN >&nbsp; </SPAN>For her to be a reluctant hero she had to be a girl.<SPAN >&nbsp; </SPAN>The show doesn’t work if Juniper is embracing this role 100%.<SPAN >&nbsp; </SPAN>For me, it seemed like a boy would just be way too into being the superhero.<SPAN >&nbsp; </SPAN>And there is something so cool about a character that can be so cute and so strong.<SPAN >&nbsp; </SPAN>She can leap from buildings, throw a car and punch out a monster that weighs three tons, but she is still very girly.<SPAN >&nbsp; </SPAN>She has really long hair, likes to look cute and has crushes on boys.<SPAN >&nbsp; </SPAN>I wanted to do a show where a girl can be a great protagonist, like Buffy or Xena.<SPAN >&nbsp; </SPAN>They can be beautiful and still be enormously tough.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P></DIV><B><SPAN ><BR ></SPAN></B>
<SPAN >Q:</SPAN><SPAN ><SPAN >&nbsp; </SPAN>How did the show end up on Cartoon Network?</SPAN>
<P ><SPAN >A:<SPAN >&nbsp; </SPAN>When I was graduating from college, I had a development deal for <I>Nuts and Bolts</I>, my comic strip from college.<SPAN >&nbsp; </SPAN>Eventually, the book got in the hands of [former Cartoon Network development executive] Linda Simensky, who was at another network at the time, and she wanted to develop it as a show.<SPAN >&nbsp; </SPAN>We spent the rest of the year developing it, but didn’t go to pilot on it.<SPAN >&nbsp; </SPAN>I was working on the show and interviewing with MTV for <I>The Real World</I> all at the same time. <SPAN >&nbsp;</SPAN>But Linda and I hit it off; she became a mentor to me, and I continued to send her ideas.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<P ><SPAN >I actually developed Juniper Lee for another network but got cold feet because they wanted it to be an educational show.<SPAN >&nbsp; </SPAN>It seemed to me that we were taking the guts out of the show.<SPAN >&nbsp; </SPAN>Luckily, they ended up passing.<SPAN >&nbsp; </SPAN>So I sent the whole package immediately to Linda, and she called me a month later and over an hour and half into the conversation, she casually told me that Cartoon Network wanted to option the show!</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<SPAN >Q:</SPAN><SPAN ><SPAN >&nbsp; </SPAN>How did you go about putting together your all-star cast and crew on the show?</SPAN>
<P ><SPAN >A:<SPAN >&nbsp; </SPAN>It is smart to surround yourself with people who are smarter and more talented that you are, and that is basically what I have done.<SPAN >&nbsp; </SPAN>As far as the cast, we just threw the net open and got really really lucky.<SPAN >&nbsp; </SPAN>We have Carlos Alazraqui, Kath Soucie and Candi Milo, who are huge heavy-hitters in the world of voice talent and are three of our regulars.<SPAN >&nbsp; </SPAN>We have Amy Hill, who has done the voice of every Asian grandmother on the planet, but with Ah-Mah she gets to do a really funny and smart spin.<SPAN >&nbsp; </SPAN>And we have Lara Jill Miller, the child actress and star from <I>Gimme A Break!</I> doing the voice of Juniper Lee.<SPAN >&nbsp; </SPAN>Juniper Lee is tough and beats up monsters, so I wanted someone who could be tough, but still really sweet and fun.<SPAN >&nbsp;&nbsp; </SPAN>We have this really amazing cast that can do anything.<SPAN >&nbsp; </SPAN>They are a complete encyclopedia of voices.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<P ><SPAN >As far as the crew, we were lucky enough to get Frank Squillace, who spent five years doing the <I>Jackie Chan Adventures</I>.<SPAN >&nbsp; </SPAN>Alan Bodner, who was the art director on <I >The</I> <I>Iron Giant,</I> which some people view as the most beautiful animated film ever made, is producing a look rarely seen on television for the show.<SPAN >&nbsp; </SPAN>And Mike Kunkel, who is such a talented artist, doing character designs and backgrounds.<SPAN >&nbsp; </SPAN>We have sort of gone back to a classic animation style – bright palettes and representational characters that look like something between classic Disney and Warner Bros. old school stuff.<SPAN >&nbsp;&nbsp; </SPAN>Plus, we have a rocking score done by Stewart Copeland, composer and former drummer of The Police.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<SPAN >Q:</SPAN><SPAN ><SPAN >&nbsp; </SPAN>What were some of your influences growing up and do they influence the show?</SPAN>
<P ><SPAN >A:<SPAN >&nbsp; </SPAN>The cartoons I love were split right down the middle between superhero shows, <I>Superfriends</I> and <I>Spiderman</I>, to classic Warner Bros. cartoons, most of the Chuck Jones stuff like Bugs Bunny, Road Runner and Pepe LePew.<SPAN >&nbsp; </SPAN>You can see a lot of Chuck Jones in the show.<SPAN >&nbsp; </SPAN><I>The Life &amp; Times of Juniper Lee</I> is also like a superhero show.<SPAN >&nbsp; </SPAN>It is loaded with action. <SPAN >&nbsp;</SPAN>All the physical humor comes through in the characters. They are really expressive, funny and sarcastic and can pull off these amazing butt-kicking fights.<SPAN >&nbsp; </SPAN>It is a real true comedic adventure show, rather than an action with some jokes or a comedy show with physical humor trying to come across as action.<SPAN >&nbsp; </SPAN>Ours is both.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<P ><SPAN >Q:</SPAN><SPAN ><STRONG><SPAN >&nbsp; </SPAN>Tell us more about the look of the show.</STRONG></SPAN></P>
<P ><SPAN >A:<SPAN >&nbsp; </SPAN>The fictional town of Orchid Bay is basically San Francisco.<SPAN >&nbsp; </SPAN>San Francisco is a very European city with all these beautiful houses and different and specific architecture that I really wanted to replicate in Orchid Bay.<SPAN >&nbsp; </SPAN>We have cable cars, painted lady houses, gigantic hills and parks, blimps and old architecture.<SPAN >&nbsp; </SPAN>The city itself is practically another character, which is what we wanted.<SPAN >&nbsp; </SPAN>We wanted it to have its own environment and own feel.<SPAN >&nbsp; </SPAN>Right from the beginning, Alan Bodner, Frank Squillace and I sat down and created a map of what the city would look like.<SPAN >&nbsp; </SPAN>It is very specific and gives the show a spine and a sense of place.<SPAN >&nbsp; </SPAN>That being said, when Juniper does her magic, she enters different worlds.<SPAN >&nbsp; </SPAN>From the underworld to the land of sleep to wherever the adventure might take her, the look and feel always changes.</SPAN></P>
<SPAN >&nbsp;</SPAN>
<SPAN >Q:</SPAN><SPAN ><SPAN >&nbsp; </SPAN>How did you get into animation from your comics background?</SPAN>
<P ><SPAN >A:<SPAN >&nbsp; </SPAN>Growing up, all I wanted to do was comic strips like <I>Doonesbury </I>or <I>Bloom County</I>.<SPAN >&nbsp; </SPAN>I made comics for years and got a nationally syndicated comic strip called <I>Frumpy the Clown</I>.<SPAN >&nbsp; </SPAN>But always, in the back of my mind, I was thinking, “I can’t wait for the strip to become big enough to do the animation special.”</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<P ><SPAN >I always wanted to bring the characters to life and do a show.<SPAN >&nbsp; </SPAN>From doing comic strips, I fell in love with doing long-form storytelling like comic books, ranging from the blue, dirty humor I do in my independent comics like <I>The Adventures of Barry Ween, Boy Genius </I>to the mainstream comics with <I>Batman</I> and <I>Green Arrow</I>.<SPAN >&nbsp; </SPAN>But with <I>The Life &amp; Times of Juniper Lee,</I> the characters get to move, talk, yell and jump around.<SPAN >&nbsp; </SPAN>When you are doing comics, you kind of wish you could animate it all.<SPAN >&nbsp; </SPAN>You get to be the director and producer of the pages with comic books, but with animation, the characters get to come to life.<SPAN >&nbsp; </SPAN>It is so much fun.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<SPAN >Q:</SPAN><SPAN ><SPAN >&nbsp; </SPAN>How did your background in comics inform your storytelling for Juniper Lee?</SPAN>
<P ><SPAN >A:<SPAN >&nbsp; </SPAN>With comics, when writing your scripts and drawing your stories, you do the whole thing, soup-to-nuts.<SPAN >&nbsp; </SPAN>You are simultaneously putting the words in the character’s mouth, placing them in the environments, designing what they look like and then executing the acting.<SPAN >&nbsp; </SPAN>When doing a show and coming up with the characters, I know exactly how they move and act and what they are wearing, and what they are holding.<SPAN >&nbsp; </SPAN>It is all there.<SPAN >&nbsp; </SPAN>But I have many brilliant people around me who help with everything.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<P ><SPAN >Q:</SPAN><SPAN ><STRONG><SPAN >&nbsp; </SPAN>Comic books are usually read by boys.<SPAN >&nbsp; </SPAN>What is it like to write for a younger, more gender- balanced audience with <I>The Life &amp; Times of Juniper Lee</I>?</STRONG></SPAN></P>
<P ><SPAN >A:<SPAN >&nbsp; </SPAN>It is true that comics generally have an older male audience, but I have actually never written my comics that way.<SPAN >&nbsp; </SPAN>I’m equally loved and hated because I have taken an alternative view of what comics should be.<SPAN >&nbsp; </SPAN>In general, my comics have a lot of humor, even the most serious ones.<SPAN >&nbsp; </SPAN>I am writing <I>Batman</I> right now and there are a lot of jokes.<SPAN >&nbsp; </SPAN>Batman is not telling the jokes, but the other characters do.<SPAN >&nbsp; </SPAN>This has always been my style.<SPAN >&nbsp; </SPAN>But this is a comedy show and we are here to make jokes.<SPAN >&nbsp; </SPAN>Then we add a ton of great action.<SPAN >&nbsp; </SPAN>More than anything, I love really good action with great jokes.</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P>
<P ><SPAN >&nbsp;</SPAN></P><br>Source: Cartoon Network Pressroom (Now defunct)</span>
<?php include "../footer.html"; ?>